from bpi._generated.audio_models import (
    AudioCollection,
    AudioCollectionsListData,
    AudioCollectionStatistic,
    AudioHotMenu,
    AudioHotMenuData,
    AudioHotMenuStatistic,
    AudioInfoData,
    AudioMember,
    AudioMemberType,
    AudioQualityInfo,
    AudioRankDetailData,
    AudioRankItem,
    AudioRankMenu,
    AudioRankMenuData,
    AudioRankMenuStatistic,
    AudioRankMusicItem,
    AudioRankMusicListData,
    AudioRankPeriod,
    AudioRankPeriodData,
    AudioStatistic,
    AudioStatusNumberData,
    AudioStreamUrlData,
    AudioStreamUrlWebData,
    AudioTag,
    AudioVipInfo,
)

from .actions import PromptData

__all__ = [
    "AudioCollection",
    "AudioCollectionsListData",
    "AudioCollectionStatistic",
    "AudioHotMenu",
    "AudioHotMenuData",
    "AudioHotMenuStatistic",
    "AudioInfoData",
    "AudioMember",
    "AudioMemberType",
    "AudioQualityInfo",
    "AudioRankDetailData",
    "AudioRankItem",
    "AudioRankMenu",
    "AudioRankMenuData",
    "AudioRankMenuStatistic",
    "AudioRankMusicItem",
    "AudioRankMusicListData",
    "AudioRankPeriod",
    "AudioRankPeriodData",
    "AudioStatistic",
    "AudioStatusNumberData",
    "AudioStreamUrlData",
    "AudioStreamUrlWebData",
    "AudioTag",
    "AudioVipInfo",
    "PromptData",
]
