# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import ConfigDict, TypeAdapter

from bpi._core.params import integer
from bpi.errors import InvalidParameterError

from .audio_models import (
    AudioCollection,
    AudioCollectionsListData,
    AudioHotMenuData,
    AudioInfoData,
    AudioMemberType,
    AudioRankDetailData,
    AudioRankMenuData,
    AudioRankMusicListData,
    AudioRankPeriodData,
    AudioStatusNumberData,
    AudioStreamUrlData,
    AudioStreamUrlWebData,
    AudioTag,
)

if TYPE_CHECKING:
    from bpi.client import AsyncBpiClient

_INFO = TypeAdapter(AudioInfoData)
_TAGS = TypeAdapter(list[AudioTag])
_MEMBERS = TypeAdapter(list[AudioMemberType])
_LYRIC = TypeAdapter(str, config=ConfigDict(strict=True))
_STATUS_NUMBER = TypeAdapter(AudioStatusNumberData)
_COLLECTION_STATUS = TypeAdapter(bool, config=ConfigDict(strict=True))
_COIN_COUNT = TypeAdapter(int, config=ConfigDict(strict=True))
_STREAM_URL_WEB = TypeAdapter(AudioStreamUrlWebData)
_STREAM_URL = TypeAdapter(AudioStreamUrlData)
_COLLECTIONS_LIST = TypeAdapter(AudioCollectionsListData)
_COLLECTION_INFO: TypeAdapter[AudioCollection | None] = TypeAdapter(AudioCollection | None)
_HOT_MENU = TypeAdapter(AudioHotMenuData)
_RANK_MENU = TypeAdapter(AudioRankMenuData)
_RANK_PERIOD = TypeAdapter(AudioRankPeriodData)
_RANK_DETAIL = TypeAdapter(AudioRankDetailData)
_RANK_MUSIC_LIST = TypeAdapter(AudioRankMusicListData)


class AudioReadMethods:
    def __init__(self, client: AsyncBpiClient) -> None:
        self._client = client

    async def info(self, *, sid: int) -> AudioInfoData:
        """audio.info; public-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/song/info", params, _INFO, host="www.bilibili.com"
        )

    async def tags(self, *, sid: int) -> list[AudioTag]:
        """audio.tags; public-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/tag/song", params, _TAGS, host="www.bilibili.com"
        )

    async def members(self, *, sid: int) -> list[AudioMemberType]:
        """audio.members; public-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/member/song", params, _MEMBERS, host="www.bilibili.com"
        )

    async def lyric(self, *, sid: int) -> str:
        """audio.lyric; public-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/song/lyric", params, _LYRIC, host="www.bilibili.com"
        )

    async def status_number(self, *, sid: int) -> AudioStatusNumberData:
        """audio.status_number; public-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/stat/song", params, _STATUS_NUMBER, host="www.bilibili.com"
        )

    async def collection_status(self, *, sid: int) -> bool:
        """audio.collection_status; authenticated-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/collections/songs-coll",
            params,
            _COLLECTION_STATUS,
            host="www.bilibili.com",
        )

    async def coin_count(self, *, sid: int) -> int:
        """audio.coin_count; authenticated-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/coin/audio", params, _COIN_COUNT, host="www.bilibili.com"
        )

    async def stream_url_web(
        self, *, sid: int, quality: int = 2, privilege: int = 2
    ) -> AudioStreamUrlWebData:
        """audio.stream_url_web; public-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        params["quality"] = integer(quality, "quality", 0)
        if quality not in [0, 1, 2, 3]:
            raise InvalidParameterError("Unsupported quality")
        params["privilege"] = integer(privilege, "privilege", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/url", params, _STREAM_URL_WEB, host="www.bilibili.com"
        )

    async def stream_url(
        self,
        *,
        song_id: int,
        quality: int,
        privilege: int = 2,
        mid: int = 2,
        platform: str = "android",
    ) -> AudioStreamUrlData:
        """audio.stream_url; public-read."""
        params: dict[str, str] = {}
        params["songid"] = integer(song_id, "song_id", 1)
        params["quality"] = integer(quality, "quality", 0)
        if quality not in [0, 1, 2, 3]:
            raise InvalidParameterError("Unsupported quality")
        params["privilege"] = integer(privilege, "privilege", 1)
        params["mid"] = integer(mid, "mid", 1)
        if not isinstance(platform, str):
            raise InvalidParameterError("platform must be a string")
        params["platform"] = platform
        params["platform"] = platform.strip()
        if not params["platform"]:
            raise InvalidParameterError("platform cannot be blank")
        return await self._client._get_payload("/audio/music-service-c/url", params, _STREAM_URL)

    async def collections_list(self, *, page: int, page_size: int) -> AudioCollectionsListData:
        """audio.collections_list; authenticated-read."""
        params: dict[str, str] = {}
        params["pn"] = integer(page, "page", 1)
        params["ps"] = integer(page_size, "page_size", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/collections/list",
            params,
            _COLLECTIONS_LIST,
            host="www.bilibili.com",
        )

    async def collection_info(self, *, sid: int) -> AudioCollection | None:
        """audio.collection_info; authenticated-read."""
        params: dict[str, str] = {}
        params["sid"] = integer(sid, "sid", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/collections/info",
            params,
            _COLLECTION_INFO,
            host="www.bilibili.com",
            optional=True,
        )

    async def hot_menu(self, *, page: int, page_size: int) -> AudioHotMenuData:
        """audio.hot_menu; public-read."""
        params: dict[str, str] = {}
        params["pn"] = integer(page, "page", 1)
        params["ps"] = integer(page_size, "page_size", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/menu/hit", params, _HOT_MENU, host="www.bilibili.com"
        )

    async def rank_menu(self, *, page: int, page_size: int) -> AudioRankMenuData:
        """audio.rank_menu; public-read."""
        params: dict[str, str] = {}
        params["pn"] = integer(page, "page", 1)
        params["ps"] = integer(page_size, "page_size", 1)
        return await self._client._get_payload(
            "/audio/music-service-c/web/menu/rank", params, _RANK_MENU, host="www.bilibili.com"
        )

    async def rank_period(self, *, list_type: int) -> AudioRankPeriodData:
        """audio.rank_period; public-read."""
        params: dict[str, str] = {}
        params["list_type"] = integer(list_type, "list_type", 1)
        params["csrf"] = self._client._csrf(host="api.bilibili.com", optional=True)
        return await self._client._get_payload(
            "/x/copyright-music-publicity/toplist/all_period", params, _RANK_PERIOD
        )

    async def rank_detail(self, *, list_id: int) -> AudioRankDetailData:
        """audio.rank_detail; public-read."""
        params: dict[str, str] = {}
        params["list_id"] = integer(list_id, "list_id", 1)
        params["csrf"] = self._client._csrf(host="api.bilibili.com", optional=True)
        return await self._client._get_payload(
            "/x/copyright-music-publicity/toplist/detail", params, _RANK_DETAIL
        )

    async def rank_music_list(self, *, list_id: int) -> AudioRankMusicListData:
        """audio.rank_music_list; public-read."""
        params: dict[str, str] = {}
        params["list_id"] = integer(list_id, "list_id", 1)
        params["csrf"] = self._client._csrf(host="api.bilibili.com", optional=True)
        return await self._client._get_payload(
            "/x/copyright-music-publicity/toplist/music_list", params, _RANK_MUSIC_LIST
        )
