# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

import builtins

from pydantic import Field, JsonValue

from bpi._core.response import ResponseModel


class AudioStatistic(ResponseModel):
    """Source: src/audio/info.rs:66:AudioStatistic."""

    sid: int
    play: int
    collect: int
    comment: int
    share: int


class AudioVipInfo(ResponseModel):
    """Source: src/audio/info.rs:81:AudioVipInfo."""

    type: int
    status: int
    due_date: int
    vip_pay_type: int


class AudioInfoData(ResponseModel):
    """Source: src/audio/info.rs:9:AudioInfoData."""

    id: int
    uid: int
    uname: str
    author: str
    title: str
    cover: str
    intro: str
    lyric: str
    crtype: int
    duration: int
    passtime: int
    curtime: int
    aid: int
    bvid: str
    cid: int
    msid: int
    attr: int
    limit: int
    activity_id: int = Field(alias="activityId")
    limitdesc: str
    ctime: JsonValue | None = Field(default=None)
    statistic: AudioStatistic
    vip_info: AudioVipInfo = Field(alias="vipInfo")
    collect_ids: list[int] = Field(alias="collectIds")
    coin_num: int


class AudioTag(ResponseModel):
    """Source: src/audio/info.rs:94:AudioTag."""

    type: str
    subtype: int
    key: int
    info: str


class AudioMember(ResponseModel):
    """Source: src/audio/info.rs:116:AudioMember."""

    mid: int
    name: str
    member_id: int


class AudioMemberType(ResponseModel):
    """Source: src/audio/info.rs:107:AudioMemberType."""

    list: builtins.list[AudioMember]
    type: int


class AudioStatusNumberData(ResponseModel):
    """Source: src/audio/status_number.rs:7:AudioStatusNumberData."""

    sid: int
    play: int
    collect: int
    comment: int
    share: int


class AudioStreamUrlWebData(ResponseModel):
    """Source: src/audio/musicstream_url.rs:26:AudioStreamUrlWebData."""

    sid: int
    type: int
    info: str
    timeout: int
    size: int
    cdns: list[str]
    qualities: JsonValue | None = Field(default=None)
    title: str
    cover: str


class AudioQualityInfo(ResponseModel):
    """Source: src/audio/musicstream_url.rs:52:AudioQualityInfo."""

    type: int
    desc: str
    size: int
    bps: str
    tag: str
    require: int
    requiredesc: str


class AudioStreamUrlData(ResponseModel):
    """Source: src/audio/musicstream_url.rs:39:AudioStreamUrlData."""

    sid: int
    type: int
    info: str
    timeout: int
    size: int
    cdns: list[str]
    qualities: list[AudioQualityInfo]
    title: str
    cover: str


class AudioCollectionStatistic(ResponseModel):
    """Source: src/audio/music_list.rs:42:AudioCollectionStatistic."""

    sid: int
    play: int
    collect: int
    comment: int | None = Field(default=None)
    share: int


class AudioCollection(ResponseModel):
    """Source: src/audio/music_list.rs:24:AudioCollection."""

    id: int
    uid: int
    uname: str
    title: str
    type: int
    published: int
    cover: str
    ctime: int
    song: int
    desc: str
    sids: list[int]
    menu_id: int = Field(alias="menuId")
    statistic: AudioCollectionStatistic


class AudioCollectionsListData(ResponseModel):
    """Source: src/audio/music_list.rs:7:AudioCollectionsListData."""

    cur_page: int = Field(alias="curPage")
    page_count: int = Field(alias="pageCount")
    total_size: int = Field(alias="totalSize")
    page_size: int = Field(alias="pageSize")
    data: list[AudioCollection]


class AudioHotMenuStatistic(ResponseModel):
    """Source: src/audio/music_list.rs:104:AudioHotMenuStatistic."""

    sid: int
    play: int
    collect: int
    comment: int
    share: int


class AudioHotMenu(ResponseModel):
    """Source: src/audio/music_list.rs:68:AudioHotMenu."""

    menu_id: int = Field(alias="menuId")
    uid: int
    uname: str
    title: str
    cover: str
    intro: str
    type: int
    off: int
    ctime: int
    curtime: int
    statistic: AudioHotMenuStatistic
    snum: int
    attr: int
    is_default: int = Field(alias="isDefault")
    collection_id: int = Field(alias="collectionId")


class AudioHotMenuData(ResponseModel):
    """Source: src/audio/music_list.rs:51:AudioHotMenuData."""

    cur_page: int = Field(alias="curPage")
    page_count: int = Field(alias="pageCount")
    total_size: int = Field(alias="totalSize")
    page_size: int = Field(alias="pageSize")
    data: list[AudioHotMenu]


class AudioRankMenuStatistic(ResponseModel):
    """Source: src/audio/music_list.rs:168:AudioRankMenuStatistic."""

    sid: int
    play: int
    collect: int
    comment: int
    share: int


class AudioRankItem(ResponseModel):
    """Source: src/audio/music_list.rs:177:AudioRankItem."""

    id: int
    title: str
    duration: int


class AudioRankMenu(ResponseModel):
    """Source: src/audio/music_list.rs:130:AudioRankMenu."""

    menu_id: int = Field(alias="menuId")
    uid: int
    uname: str
    title: str
    cover: str
    intro: str
    type: int
    off: int
    ctime: int
    curtime: int
    statistic: AudioRankMenuStatistic
    snum: int
    attr: int
    is_default: int = Field(alias="isDefault")
    collection_id: int = Field(alias="collectionId")
    audios: list[AudioRankItem]


class AudioRankMenuData(ResponseModel):
    """Source: src/audio/music_list.rs:113:AudioRankMenuData."""

    cur_page: int = Field(alias="curPage")
    page_count: int = Field(alias="pageCount")
    total_size: int = Field(alias="totalSize")
    page_size: int = Field(alias="pageSize")
    data: list[AudioRankMenu]


class AudioRankPeriod(ResponseModel):
    """Source: src/audio/rank.rs:20:AudioRankPeriod."""

    id: int = Field(alias="ID")
    priod: int
    publish_time: int


class AudioRankPeriodData(ResponseModel):
    """Source: src/audio/rank.rs:15:AudioRankPeriodData."""

    list: dict[str, list[AudioRankPeriod]]


class AudioRankDetailData(ResponseModel):
    """Source: src/audio/rank.rs:28:AudioRankDetailData."""

    listen_fid: int
    all_fid: int
    fav_mid: int
    cover_url: str
    is_subscribe: bool
    listen_count: int


class AudioRankMusicItem(ResponseModel):
    """Source: src/audio/rank.rs:43:AudioRankMusicItem."""

    music_id: str
    music_title: str
    singer: str
    album: str
    mv_aid: int
    mv_bvid: str
    mv_cover: str
    heat: int
    rank: int
    can_listen: bool
    recommendation: str
    creation_aid: int
    creation_bvid: str
    creation_cover: str
    creation_title: str
    creation_up: int
    creation_nickname: str
    creation_duration: int
    creation_play: int
    creation_reason: str
    achievements: list[str]
    material_id: int
    material_use_num: int
    material_duration: int
    material_show: int
    song_type: int


class AudioRankMusicListData(ResponseModel):
    """Source: src/audio/rank.rs:38:AudioRankMusicListData."""

    list: builtins.list[AudioRankMusicItem]
