# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import TypeAdapter

from bpi._core.params import integer
from bpi.errors import InvalidParameterError

from .bangumi_models import (
    BangumiDetailResult,
    BangumiInfoResult,
    BangumiSectionResult,
    BangumiTimelineDay,
)

if TYPE_CHECKING:
    from bpi.client import AsyncBpiClient

_INFO = TypeAdapter(BangumiInfoResult)
_TIMELINE = TypeAdapter(list[BangumiTimelineDay])
_DETAIL_BY_SEASON_ID = TypeAdapter(BangumiDetailResult)
_DETAIL_BY_EP_ID = TypeAdapter(BangumiDetailResult)
_SECTIONS = TypeAdapter(BangumiSectionResult)


class BangumiReadMethods:
    def __init__(self, client: AsyncBpiClient) -> None:
        self._client = client

    async def info(self, *, media_id: int) -> BangumiInfoResult:
        """bangumi.info.review_user; public-read."""
        params: dict[str, str] = {}
        params["media_id"] = integer(media_id, "media_id", 1)
        return await self._client._get_payload("/pgc/review/user", params, _INFO)

    async def timeline(self, *, types: int, before: int, after: int) -> list[BangumiTimelineDay]:
        """bangumi.timeline; public-read."""
        params: dict[str, str] = {}
        params["types"] = integer(types, "types", 1)
        if types not in [1, 3, 4]:
            raise InvalidParameterError("Unsupported types")
        params["before"] = integer(before, "before", 0)
        if before > 7:
            raise InvalidParameterError("before exceeds 7")
        params["after"] = integer(after, "after", 0)
        if after > 7:
            raise InvalidParameterError("after exceeds 7")
        return await self._client._get_payload("/pgc/web/timeline", params, _TIMELINE)

    async def detail_by_season_id(self, *, season_id: int) -> BangumiDetailResult:
        """bangumi.info.season_detail_by_season_id; public-read."""
        params: dict[str, str] = {}
        params["season_id"] = integer(season_id, "season_id", 1)
        return await self._client._get_payload("/pgc/view/web/season", params, _DETAIL_BY_SEASON_ID)

    async def detail_by_ep_id(self, *, episode_id: int) -> BangumiDetailResult:
        """bangumi.info.season_detail_by_ep_id; public-read."""
        params: dict[str, str] = {}
        params["ep_id"] = integer(episode_id, "episode_id", 1)
        return await self._client._get_payload("/pgc/view/web/season", params, _DETAIL_BY_EP_ID)

    async def sections(self, *, season_id: int) -> BangumiSectionResult:
        """bangumi.info.season_section; public-read."""
        params: dict[str, str] = {}
        params["season_id"] = integer(season_id, "season_id", 1)
        return await self._client._get_payload("/pgc/web/season/section", params, _SECTIONS)
