# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from pydantic import AliasChoices, Field, JsonValue

from bpi._core.response import ResponseModel
from bpi.bangumi.models import VipLabel


class BangumiAreaInfo(ResponseModel):
    """Source: src/bangumi/info.rs:198:BangumiAreaInfo."""

    id: int
    name: str


class BangumiMediaNewEp(ResponseModel):
    """Source: src/bangumi/info.rs:204:BangumiMediaNewEp."""

    id: int
    index: str
    index_show: str


class BangumiRating(ResponseModel):
    """Source: src/bangumi/info.rs:219:BangumiRating."""

    count: int
    score: float


class BangumiMedia(ResponseModel):
    """Source: src/bangumi/info.rs:182:BangumiMedia."""

    areas: list[BangumiAreaInfo]
    cover: str
    horizontal_picture: str
    media_id: int
    new_ep: BangumiMediaNewEp
    rating: BangumiRating = Field(
        default_factory=lambda: BangumiRating.model_validate({"count": 0, "score": 0.0})
    )
    season_id: int
    share_url: str
    title: str
    type: int
    type_name: str


class BangumiReview(ResponseModel):
    """Source: src/bangumi/info.rs:225:BangumiReview."""

    is_coin: int
    is_open: int


class BangumiInfoResult(ResponseModel):
    """Source: src/bangumi/info.rs:176:BangumiInfoResult."""

    media: BangumiMedia
    review: BangumiReview | None = Field(default=None)


class BangumiTimelineEpisode(ResponseModel):
    """Source: src/bangumi/timeline.rs:33:BangumiTimelineEpisode."""

    cover: str
    delay: int
    delay_id: int
    delay_index: str
    delay_reason: str
    ep_cover: str
    episode_id: int
    pub_index: str
    pub_time: str
    pub_ts: int
    published: int
    follows: str
    plays: str
    season_id: int
    square_cover: str
    title: str


class BangumiTimelineDay(ResponseModel):
    """Source: src/bangumi/timeline.rs:24:BangumiTimelineDay."""

    date: str
    date_ts: int
    day_of_week: int
    episodes: list[BangumiTimelineEpisode]
    is_today: int


class BangumiPendant(ResponseModel):
    """Source: src/bangumi/info.rs:296:BangumiPendant."""

    image: str
    name: str
    pid: int


class BangumiActivity(ResponseModel):
    """Source: src/bangumi/info.rs:286:BangumiActivity."""

    head_bg_url: str
    id: int
    title: str
    link: str | None = Field(default=None)
    pendants: list[BangumiPendant] | None = Field(default=None)
    cover: str | None = Field(default=None)


class BangumiBadgeInfo(ResponseModel):
    """Source: src/bangumi/info.rs:342:BangumiBadgeInfo."""

    bg_color: str
    bg_color_night: str
    text: str


class BangumiDimension(ResponseModel):
    """Source: src/bangumi/info.rs:349:BangumiDimension."""

    height: int
    rotate: int
    width: int


class BangumiInteraction(ResponseModel):
    """Source: src/bangumi/info.rs:356:BangumiInteraction."""

    graph_version: int
    interaction: bool


class BangumiMultiViewEp(ResponseModel):
    """Source: src/bangumi/info.rs:362:BangumiMultiViewEp."""

    ep_id: int


class BangumiEpisodeRights(ResponseModel):
    """Source: src/bangumi/info.rs:367:BangumiEpisodeRights."""

    allow_dm: int
    allow_download: int
    area_limit: int
    allow_demand: int | None = Field(default=None)


class BangumiSkipTime(ResponseModel):
    """Source: src/bangumi/info.rs:382:BangumiSkipTime."""

    end: int
    start: int


class BangumiSkip(ResponseModel):
    """Source: src/bangumi/info.rs:376:BangumiSkip."""

    ed: BangumiSkipTime | None = Field(default=None)
    op: BangumiSkipTime | None = Field(default=None)


class BangumiEpisode(ResponseModel):
    """Source: src/bangumi/info.rs:304:BangumiEpisode."""

    aid: int
    badge: str
    badge_info: BangumiBadgeInfo | None = Field(default=None)
    badge_type: int
    bvid: str
    cid: int
    cover: str
    dimension: BangumiDimension | None = Field(default=None)
    duration: int
    enable_vt: bool
    ep_id: int
    from_: str = Field(alias="from")
    id: int
    interaction: BangumiInteraction | None = Field(default=None)
    is_view_hide: bool
    link: str
    long_title: str
    multi_view_eps: list[BangumiMultiViewEp] | None = Field(default=None)
    pub_time: int
    pv: int
    release_date: str
    rights: BangumiEpisodeRights | None = Field(default=None)
    section_type: int
    share_copy: str
    share_url: str
    short_link: str
    show_title: str
    show_drm_login_dialog: bool = Field(alias="showDrmLoginDialog")
    skip: BangumiSkip | None = Field(default=None)
    status: int
    subtitle: str
    title: str
    vid: str


class BangumiFreya(ResponseModel):
    """Source: src/bangumi/info.rs:388:BangumiFreya."""

    bubble_desc: str = Field(default="")
    bubble_show_cnt: int
    icon_show: int


class BangumiIconFont(ResponseModel):
    """Source: src/bangumi/info.rs:396:BangumiIconFont."""

    name: str
    text: str


class BangumiMultiViewInfo(ResponseModel):
    """Source: src/bangumi/info.rs:402:BangumiMultiViewInfo."""

    changing_dance: str
    is_multi_view_season: bool


class BangumiDetailNewEp(ResponseModel):
    """Source: src/bangumi/info.rs:211:BangumiDetailNewEp."""

    id: int
    desc: str
    is_new: int
    title: str


class BangumiPayType(ResponseModel):
    """Source: src/bangumi/info.rs:423:BangumiPayType."""

    allow_discount: int
    allow_pack: int
    allow_ticket: int
    allow_time_limit: int
    allow_vip_discount: int
    forbid_bb: int


class BangumiPayment(ResponseModel):
    """Source: src/bangumi/info.rs:408:BangumiPayment."""

    discount: int
    pay_type: BangumiPayType
    price: str
    promotion: str
    tip: str = Field(default="")
    view_start_time: int
    vip_discount: int
    vip_first_promotion: str
    vip_price: str
    vip_promotion: str


class BangumiPayPack(ResponseModel):
    """Source: src/bangumi/info.rs:433:BangumiPayPack."""

    id: int
    not_paid_text_for_app: str
    paid_text_for_app: str
    pay_pack_url: str
    status: int
    title: str


class BangumiPlayStrategy(ResponseModel):
    """Source: src/bangumi/info.rs:443:BangumiPlayStrategy."""

    strategies: list[JsonValue]


class BangumiPositive(ResponseModel):
    """Source: src/bangumi/info.rs:448:BangumiPositive."""

    id: int
    title: str


class BangumiPublish(ResponseModel):
    """Source: src/bangumi/info.rs:454:BangumiPublish."""

    is_finish: int
    is_started: int
    pub_time: str
    pub_time_show: str
    unknow_pub_date: int
    weekday: int


class BangumiRights(ResponseModel):
    """Source: src/bangumi/info.rs:464:BangumiRights."""

    allow_bp: int
    allow_bp_rank: int
    allow_download: int
    allow_review: int
    area_limit: int
    ban_area_show: int
    can_watch: int
    copyright: str
    forbid_pre: int
    freya_white: int
    is_cover_show: int
    is_preview: int
    only_vip_download: int
    resource: str
    watch_platform: int


class BangumiSeasonNewEp(ResponseModel):
    """Source: src/bangumi/info.rs:501:BangumiSeasonNewEp."""

    cover: str
    id: int
    index_show: str


class BangumiSeasonStat(ResponseModel):
    """Source: src/bangumi/info.rs:508:BangumiSeasonStat."""

    favorites: int
    series_follow: int
    views: int
    vt: int


class BangumiSeason(ResponseModel):
    """Source: src/bangumi/info.rs:483:BangumiSeason."""

    badge: str
    badge_info: BangumiBadgeInfo | None = Field(default=None)
    badge_type: int
    cover: str
    enable_vt: bool
    horizontal_cover_1610: str
    horizontal_cover_169: str
    icon_font: BangumiIconFont | None = Field(default=None)
    media_id: int
    new_ep: BangumiSeasonNewEp | None = Field(default=None)
    season_id: int
    season_title: str
    season_type: int
    stat: BangumiSeasonStat | None = Field(default=None)


class BangumiReport(ResponseModel):
    """Source: src/bangumi/info.rs:577:BangumiReport."""

    aid: str = Field(default="")
    ep_title: str = Field(default="")
    position: str = Field(default="")
    season_id: str = Field(default="")
    season_type: str = Field(default="")
    section_id: str = Field(default="")
    section_type: str = Field(default="")


class BangumiStat(ResponseModel):
    """Source: src/bangumi/info.rs:614:BangumiStat."""

    coins: int = Field(default=0, validation_alias=AliasChoices("coins", "coin"))
    danmakus: int = Field(default=0)
    favorite: int = Field(default=0)
    favorites: int = Field(default=0)
    follow_text: str = Field(default="")
    hot: int | None = Field(default=None)
    likes: int = Field(default=0)
    reply: int = Field(default=0)
    share: int = Field(default=0)
    views: int = Field(default=0, validation_alias=AliasChoices("views", "play"))
    vt: int = Field(default=0)


class BangumiDanmaku(ResponseModel):
    """Source: src/bangumi/info.rs:597:BangumiDanmaku."""

    icon: str
    pure_text: str
    text: str
    value: int


class BangumiVt(ResponseModel):
    """Source: src/bangumi/info.rs:605:BangumiVt."""

    icon: str
    pure_text: str
    text: str
    value: int


class BangumiStatForUnity(ResponseModel):
    """Source: src/bangumi/info.rs:588:BangumiStatForUnity."""

    coin: int
    danmaku: BangumiDanmaku | None = Field(default=None)
    likes: int
    reply: int
    vt: BangumiVt | None = Field(default=None)


class BangumiUpInfo(ResponseModel):
    """Source: src/bangumi/info.rs:644:BangumiUpInfo."""

    avatar: str = Field(default="")
    avatar_subscript_url: str = Field(default="")
    follower: int = Field(default=0)
    is_follow: int = Field(default=0)
    mid: int = Field(default=0)
    nickname_color: str = Field(default="")
    pendant: BangumiPendant | None = Field(default=None)
    theme_type: int = Field(default=0)
    uname: str = Field(default="")
    verify_type: int = Field(default=0)
    vip_label: VipLabel | None = Field(default=None)
    vip_status: int = Field(default=0)
    vip_type: int = Field(default=0)


class BangumiSectionEpisode(ResponseModel):
    """Source: src/bangumi/info.rs:531:BangumiSectionEpisode."""

    aid: int = Field(default=0)
    archive_attr: int | None = Field(default=None)
    badge: str = Field(default="")
    badge_info: BangumiBadgeInfo | None = Field(default=None)
    badge_type: int = Field(default=0)
    bvid: str = Field(default="")
    cid: int = Field(default=0)
    cover: str = Field(default="")
    dimension: BangumiDimension | None = Field(default=None)
    duration: int = Field(default=0)
    enable_vt: bool = Field(default=False)
    ep_id: int = Field(default=0)
    from_: str = Field(default="", alias="from")
    icon_font: BangumiIconFont | None = Field(default=None)
    id: int = Field(default=0)
    interaction: BangumiInteraction | None = Field(default=None)
    is_view_hide: bool = Field(default=False)
    link: str = Field(default="")
    link_type: str = Field(default="")
    long_title: str = Field(default="")
    pub_time: int = Field(default=0)
    pv: int = Field(default=0)
    release_date: str = Field(default="")
    report: BangumiReport | None = Field(default=None)
    rights: BangumiEpisodeRights | None = Field(default=None)
    section_type: int = Field(default=0)
    share_copy: str = Field(default="")
    share_url: str = Field(default="")
    short_link: str = Field(default="")
    show_title: str = Field(default="")
    show_drm_login_dialog: bool = Field(default=False, alias="showDrmLoginDialog")
    skip: BangumiSkip | None = Field(default=None)
    stat: BangumiStat | None = Field(default=None)
    stat_for_unity: BangumiStatForUnity | None = Field(default=None)
    status: int = Field(default=0)
    subtitle: str = Field(default="")
    title: str = Field(default="")
    toast_title: str = Field(default="")
    up_info: BangumiUpInfo | None = Field(default=None)
    vid: str = Field(default="")


class BangumiSection(ResponseModel):
    """Source: src/bangumi/info.rs:516:BangumiSection."""

    attr: int
    episode_id: int
    episode_ids: list[int] = Field(default_factory=list)
    episodes: list[BangumiSectionEpisode]
    id: int
    report: BangumiReport | None = Field(default=None)
    title: str
    type: int
    type2: int


class BangumiSeries(ResponseModel):
    """Source: src/bangumi/info.rs:631:BangumiSeries."""

    display_type: int
    series_id: int
    series_title: str


class BangumiShow(ResponseModel):
    """Source: src/bangumi/info.rs:638:BangumiShow."""

    wide_screen: int


class BangumiUserStatus(ResponseModel):
    """Source: src/bangumi/info.rs:661:BangumiUserStatus."""

    area_limit: int
    ban_area_show: int
    follow: int
    follow_status: int
    login: int
    pay: int
    pay_pack_paid: int
    sponsor: int


class BangumiDetailResult(ResponseModel):
    """Source: src/bangumi/info.rs:231:BangumiDetailResult."""

    activity: BangumiActivity | None = Field(default=None)
    actors: str
    alias: str
    areas: list[BangumiAreaInfo]
    bkg_cover: str
    cover: str
    delivery_fragment_video: bool
    enable_vt: bool
    episodes: list[BangumiEpisode]
    evaluate: str
    freya: BangumiFreya | None = Field(default=None)
    hide_ep_vv_vt_dm: int
    icon_font: BangumiIconFont | None = Field(default=None)
    jp_title: str
    link: str
    media_id: int
    mode: int
    multi_view_info: BangumiMultiViewInfo | None = Field(default=None)
    new_ep: BangumiDetailNewEp
    payment: BangumiPayment | None = Field(default=None)
    pay_pack: BangumiPayPack | None = Field(default=None, alias="payPack")
    play_strategy: BangumiPlayStrategy | None = Field(default=None)
    positive: BangumiPositive | None = Field(default=None)
    publish: BangumiPublish
    rating: BangumiRating | None = Field(default=None)
    record: str
    rights: BangumiRights
    season_id: int
    season_title: str
    seasons: list[BangumiSeason]
    section: list[BangumiSection] | None = Field(default=None)
    section_bottom_desc: str | None = Field(default=None)
    series: BangumiSeries | None = Field(default=None)
    share_copy: str
    share_sub_title: str
    share_url: str
    show: BangumiShow | None = Field(default=None)
    show_season_type: int
    square_cover: str
    staff: str
    stat: BangumiStat
    status: int
    styles: list[str]
    subtitle: str
    title: str
    total: int
    type: int
    up_info: BangumiUpInfo | None = Field(default=None)
    user_status: BangumiUserStatus | None = Field(default=None)


class BangumiSectionEpisodeInfo(ResponseModel):
    """Source: src/bangumi/info.rs:688:BangumiSectionEpisodeInfo."""

    aid: int
    badge: str
    badge_info: BangumiBadgeInfo
    badge_type: int
    cid: int
    cover: str
    from_: str = Field(alias="from")
    id: int
    is_premiere: int
    long_title: str
    share_url: str
    status: int
    title: str
    vid: str


class BangumiMainSection(ResponseModel):
    """Source: src/bangumi/info.rs:680:BangumiMainSection."""

    episodes: list[BangumiSectionEpisodeInfo]
    id: int
    type: int
    title: str


class BangumiSectionResult(ResponseModel):
    """Source: src/bangumi/info.rs:673:BangumiSectionResult."""

    main_section: BangumiMainSection = Field(
        default_factory=lambda: BangumiMainSection.model_validate(
            {"episodes": [], "id": 0, "type": 0, "title": ""}
        )
    )
    section: list[BangumiMainSection]
