# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from pydantic import Field

from bpi._core.response import ResponseModel


class CourseBriefImg(ResponseModel):
    """Source: src/cheese/info.rs:48:CourseBriefImg."""

    aspect_ratio: float
    url: str


class CourseBrief(ResponseModel):
    """Source: src/cheese/info.rs:40:CourseBrief."""

    content: str
    img: list[CourseBriefImg]
    title: str
    type: int


class CourseCoupon(ResponseModel):
    """Source: src/cheese/info.rs:54:CourseCoupon."""

    amount: float
    expire_time: str
    start_time: str
    status: int
    title: str
    token: str


class CourseEpisodePage(ResponseModel):
    """Source: src/cheese/info.rs:64:CourseEpisodePage."""

    next: bool
    num: int
    size: int
    total: int


class CourseEpisode(ResponseModel):
    """Source: src/cheese/info.rs:72:CourseEpisode."""

    aid: int
    cid: int
    duration: int
    from_: str = Field(alias="from")
    id: int
    index: int
    page: int
    play: int
    release_date: int
    status: int
    title: str
    watched: bool
    watched_history: int = Field(alias="watchedHistory")


class CourseFaq(ResponseModel):
    """Source: src/cheese/info.rs:90:CourseFaq."""

    content: str
    link: str
    title: str


class CourseFaqItem(ResponseModel):
    """Source: src/cheese/info.rs:103:CourseFaqItem."""

    answer: str
    question: str


class CourseFaq1(ResponseModel):
    """Source: src/cheese/info.rs:97:CourseFaq1."""

    items: list[CourseFaqItem]
    title: str


class CoursePayment(ResponseModel):
    """Source: src/cheese/info.rs:109:CoursePayment."""

    desc: str
    discount_desc: str
    discount_prefix: str = Field(default="")
    pay_shade: str
    price: float
    price_format: str


class CoursePurchaseNote(ResponseModel):
    """Source: src/cheese/info.rs:120:CoursePurchaseNote."""

    content: str
    link: str
    title: str


class CoursePurchaseProtocol(ResponseModel):
    """Source: src/cheese/info.rs:127:CoursePurchaseProtocol."""

    link: str
    title: str


class CourseStat(ResponseModel):
    """Source: src/cheese/info.rs:133:CourseStat."""

    play: int
    play_desc: str


class CoursePendant(ResponseModel):
    """Source: src/cheese/info.rs:151:CoursePendant."""

    image: str
    name: str
    pid: int


class CourseUpInfo(ResponseModel):
    """Source: src/cheese/info.rs:139:CourseUpInfo."""

    avatar: str
    brief: str
    follower: int
    is_follow: int
    link: str
    mid: int
    pendant: CoursePendant
    uname: str


class CourseProgress(ResponseModel):
    """Source: src/cheese/info.rs:168:CourseProgress."""

    last_ep_id: int
    last_ep_index: str
    last_time: int


class CourseUserStatus(ResponseModel):
    """Source: src/cheese/info.rs:159:CourseUserStatus."""

    favored: int
    favored_count: int
    payed: int
    progress: CourseProgress | None = Field(default=None)


class CourseInfo(ResponseModel):
    """Source: src/cheese/info.rs:12:CourseInfo."""

    brief: CourseBrief
    coupon: CourseCoupon
    cover: str
    episode_page: CourseEpisodePage
    episode_sort: int
    episodes: list[CourseEpisode]
    faq: CourseFaq
    faq1: CourseFaq1
    payment: CoursePayment
    purchase_note: CoursePurchaseNote
    purchase_protocol: CoursePurchaseProtocol
    release_bottom_info: str
    release_info: str
    release_info2: str
    release_status: str
    season_id: int
    share_url: str
    short_link: str
    stat: CourseStat
    status: int
    subtitle: str
    title: str
    up_info: CourseUpInfo
    user_status: CourseUserStatus


class CourseEpPage(ResponseModel):
    """Source: src/cheese/info.rs:185:CourseEpPage."""

    next: bool
    num: int
    size: int
    total: int


class CourseEpList(ResponseModel):
    """Source: src/cheese/info.rs:179:CourseEpList."""

    items: list[CourseEpisode]
    page: CourseEpPage
