# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import TypeAdapter

from bpi._core.params import integer

from .cheese_models import (
    CourseEpList,
    CourseInfo,
)

if TYPE_CHECKING:
    from bpi.client import AsyncBpiClient

_INFO_BY_SEASON_ID = TypeAdapter(CourseInfo)
_INFO_BY_EP_ID = TypeAdapter(CourseInfo)
_EP_LIST = TypeAdapter(CourseEpList)


class CheeseReadMethods:
    def __init__(self, client: AsyncBpiClient) -> None:
        self._client = client

    async def info_by_season_id(self, *, season_id: int) -> CourseInfo:
        """cheese.info.season_detail_by_season_id; public-read."""
        params: dict[str, str] = {}
        params["season_id"] = integer(season_id, "season_id", 1)
        return await self._client._get_payload("/pugv/view/web/season", params, _INFO_BY_SEASON_ID)

    async def info_by_ep_id(self, *, episode_id: int) -> CourseInfo:
        """cheese.info.season_detail_by_ep_id; public-read."""
        params: dict[str, str] = {}
        params["ep_id"] = integer(episode_id, "episode_id", 1)
        return await self._client._get_payload("/pugv/view/web/season", params, _INFO_BY_EP_ID)

    async def ep_list(
        self, *, season_id: int, page_size: int | None = None, page: int | None = None
    ) -> CourseEpList:
        """cheese.info.ep_list; public-read."""
        params: dict[str, str] = {}
        params["season_id"] = integer(season_id, "season_id", 1)
        if page_size is not None:
            params["ps"] = integer(page_size, "page_size", 1)
        if page is not None:
            params["pn"] = integer(page, "page", 1)
        return await self._client._get_payload("/pugv/view/web/ep/list", params, _EP_LIST)
