# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from bpi._core.response import ResponseModel


class LoginStats(ResponseModel):
    """Source: src/login/model.rs:36:LoginStats."""

    following: int
    follower: int
    dynamic_count: int


class LoginDailyReward(ResponseModel):
    """Source: src/login/model.rs:62:LoginDailyReward."""

    login: bool
    watch: bool
    coins: int
    share: bool
    email: bool
    tel: bool
    safe_question: bool
    identify_card: bool


class LoginAccountInfo(ResponseModel):
    """Source: src/login/model.rs:83:LoginAccountInfo."""

    mid: int
    uname: str
    userid: str
    sign: str
    birthday: str
    sex: str
    nick_free: bool
    rank: str


class LoginVipInfo(ResponseModel):
    """Source: src/login/model.rs:104:LoginVipInfo."""

    mid: int
    vip_type: int
    vip_status: int
    vip_due_date: int
    vip_pay_type: int
    theme_type: int
