# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import TypeAdapter

from .login_models import LoginAccountInfo, LoginDailyReward, LoginStats, LoginVipInfo

if TYPE_CHECKING:
    from bpi.client import AsyncBpiClient

_STAT = TypeAdapter(LoginStats)
_DAILY_REWARD = TypeAdapter(LoginDailyReward)
_ACCOUNT_INFO = TypeAdapter(LoginAccountInfo)
_VIP_INFO = TypeAdapter(LoginVipInfo)


class LoginReadMethods:
    def __init__(self, client: AsyncBpiClient) -> None:
        self._client = client

    async def stat(self) -> LoginStats:
        """login.stat; private-read."""
        params: dict[str, str] = {}
        return await self._client._get_payload("/x/web-interface/nav/stat", params, _STAT)

    async def daily_reward(self) -> LoginDailyReward:
        """login.daily_reward; authenticated-read."""
        params: dict[str, str] = {}
        return await self._client._get_payload("/x/member/web/exp/reward", params, _DAILY_REWARD)

    async def account_info(self) -> LoginAccountInfo:
        """login.account_info; private-read."""
        params: dict[str, str] = {}
        return await self._client._get_payload("/x/member/web/account", params, _ACCOUNT_INFO)

    async def vip_info(self) -> LoginVipInfo:
        """login.vip_info; authenticated-read."""
        params: dict[str, str] = {}
        return await self._client._get_payload("/x/vip/web/user/info", params, _VIP_INFO)
