# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

import builtins
from typing import Annotated

from pydantic import BeforeValidator, Field, JsonValue

from bpi._core.response import ResponseModel


def _deserialize_mid_from_string_or_number(value: object) -> object:
    if type(value) is int:
        if value > 0:
            return value
        raise ValueError("mid must be positive")
    if isinstance(value, str):
        try:
            parsed = int(value)
        except ValueError:
            raise ValueError("mid must be a string or number") from None
        if parsed > 0:
            return parsed
    raise ValueError("mid must be a string or number")


def _deserialize_optional_string(value: object) -> object:
    if isinstance(value, str) and not value.strip():
        return None
    return value


class UserCardSummary(ResponseModel):
    """Source: src/user/model.rs:28:UserCardSummary."""

    mid: Annotated[int, BeforeValidator(_deserialize_mid_from_string_or_number)]
    name: str
    sex: str | None = Field(default=None)
    face: str
    sign: str = Field(default="")
    fans: int = Field(default=0)
    attention: int = Field(default=0)


class UserCardProfile(ResponseModel):
    """Source: src/user/model.rs:7:UserCardProfile."""

    card: UserCardSummary
    following: bool
    archive_count: int = Field(default=0)
    article_count: int = Field(default=0)
    follower: int = Field(default=0)
    like_num: int = Field(default=0)


class UserBatchCard(ResponseModel):
    """Source: src/user/model.rs:52:UserBatchCard."""

    mid: int
    name: str
    face: str
    sign: str = Field(default="")
    rank: int = Field(default=0)
    level: int = Field(default=0)
    silence: int = Field(default=0)


class UserBatchVip(ResponseModel):
    """Source: src/user/model.rs:113:UserBatchVip."""

    kind: int = Field(default=0, alias="type")
    status: int = Field(default=0)
    due_date: int = Field(default=0)
    vip_pay_type: int = Field(default=0)
    theme_type: int = Field(default=0)


class UserOfficialSummary(ResponseModel):
    """Source: src/user/model.rs:175:UserOfficialSummary."""

    role: int = Field(default=0)
    title: str = Field(default="")
    desc: str = Field(default="")
    kind: int = Field(default=0, alias="type")


class UserBatchInfo(ResponseModel):
    """Source: src/user/model.rs:75:UserBatchInfo."""

    mid: int
    name: str
    sign: str = Field(default="")
    rank: int = Field(default=0)
    level: int = Field(default=0)
    silence: int = Field(default=0)
    sex: Annotated[str | None, BeforeValidator(_deserialize_optional_string)] = Field(default=None)
    face: str
    vip: UserBatchVip | None = Field(default=None)
    official: UserOfficialSummary | None = Field(default=None)
    is_fake_account: int | None = Field(default=None)
    expert_info: JsonValue | None = Field(default=None)


class UserAlbumCount(ResponseModel):
    """Source: src/user/model.rs:758:UserAlbumCount."""

    all_count: int = Field(default=0)
    draw_count: int = Field(default=0)
    photo_count: int = Field(default=0)
    daily_count: int = Field(default=0)


class UserBangumiLatestEpisode(ResponseModel):
    """Source: src/user/model.rs:314:UserBangumiLatestEpisode."""

    id: int = Field(default=0)
    index_show: str = Field(default="")
    cover: str = Field(default="")
    title: str = Field(default="")
    long_title: str | None = Field(default=None)
    pub_time: str = Field(default="")
    duration: int = Field(default=0)


class UserBangumiRating(ResponseModel):
    """Source: src/user/model.rs:340:UserBangumiRating."""

    score: float = Field(default=0.0)
    count: int = Field(default=0)


class UserBangumiFollow(ResponseModel):
    """Source: src/user/model.rs:248:UserBangumiFollow."""

    season_id: int
    media_id: int
    season_type: int = Field(default=0)
    season_type_name: str = Field(default="")
    title: str = Field(default="")
    cover: str = Field(default="")
    total_count: int = Field(default=0)
    is_finish: int = Field(default=0)
    is_started: int = Field(default=0)
    is_play: int = Field(default=0)
    badge: str = Field(default="")
    badge_type: int = Field(default=0)
    latest_episode: UserBangumiLatestEpisode = Field(
        default_factory=lambda: UserBangumiLatestEpisode.model_validate(
            {
                "id": 0,
                "index_show": "",
                "cover": "",
                "title": "",
                "long_title": None,
                "pub_time": "",
                "duration": 0,
            }
        ),
        alias="new_ep",
    )
    rating: UserBangumiRating | None = Field(default=None)
    url: str = Field(default="")
    short_url: str = Field(default="")
    summary: str = Field(default="")
    styles: list[str] = Field(default_factory=list)
    follow_status: int = Field(default=0)
    progress: str = Field(default="")
    both_follow: bool = Field(default=False)


class UserBangumiFollowList(ResponseModel):
    """Source: src/user/model.rs:231:UserBangumiFollowList."""

    items: list[UserBangumiFollow] = Field(default_factory=list, alias="list")
    page: int = Field(default=0, alias="pn")
    page_size: int = Field(default=0, alias="ps")
    total: int = Field(default=0)


class UserRelationOfficialVerify(ResponseModel):
    """Source: src/user/model.rs:665:UserRelationOfficialVerify."""

    kind: int = Field(default=0, alias="type")
    desc: str = Field(default="")


class UserFollowing(ResponseModel):
    """Source: src/user/model.rs:382:UserFollowing."""

    mid: int
    attribute: int = Field(default=0)
    mtime: int = Field(default=0)
    tag: list[int] | None = Field(default=None)
    special: int = Field(default=0)
    name: str = Field(default="", alias="uname")
    face: str = Field(default="")
    sign: str = Field(default="")
    face_nft: int = Field(default=0)
    official_verify: UserRelationOfficialVerify | None = Field(default=None)
    vip: JsonValue | None = Field(default=None)


class UserFollowings(ResponseModel):
    """Source: src/user/model.rs:368:UserFollowings."""

    list: builtins.list[UserFollowing] = Field(default_factory=list)
    re_version: int = Field(default=0)
    total: int = Field(default=0)


class UserFollower(ResponseModel):
    """Source: src/user/model.rs:436:UserFollower."""

    mid: int
    attribute: int = Field(default=0)
    mtime: int | None = Field(default=None)
    tag: list[int] | None = Field(default=None)
    special: int = Field(default=0)
    contract_info: JsonValue | None = Field(default=None)
    name: str = Field(default="", alias="uname")
    face: str = Field(default="")
    sign: str = Field(default="")
    face_nft: int = Field(default=0)
    official_verify: UserRelationOfficialVerify | None = Field(default=None)
    vip: JsonValue | None = Field(default=None)


class UserFollowers(ResponseModel):
    """Source: src/user/model.rs:419:UserFollowers."""

    list: builtins.list[UserFollower] = Field(default_factory=list)
    offset: str = Field(default="")
    re_version: int = Field(default=0)
    total: int = Field(default=0)


class UserFollowTag(ResponseModel):
    """Source: src/user/model.rs:476:UserFollowTag."""

    id: int = Field(alias="tagid")
    name: str
    count: int = Field(default=0)
    tip: str | None = Field(default=None)


class UserMedalInfo(ResponseModel):
    """Source: src/user/model.rs:552:UserMedalInfo."""

    target_id: int
    level: int = Field(default=0)
    name: str = Field(default="", alias="medal_name")
    medal_color_start: int = Field(default=0)
    medal_color_end: int = Field(default=0)
    medal_color_border: int = Field(default=0)
    guard_level: int = Field(default=0)
    wearing_status: int = Field(default=0)
    medal_id: int = Field(default=0)
    intimacy: int = Field(default=0)
    next_intimacy: int = Field(default=0)
    today_feed: int = Field(default=0)
    day_limit: int = Field(default=0)
    guard_icon: str | None = Field(default=None)
    honor_icon: str | None = Field(default=None)


class UserMedalOwnerInfo(ResponseModel):
    """Source: src/user/model.rs:601:UserMedalOwnerInfo."""

    name: str = Field(default="")
    level: int = Field(default=0)
    color_start: int = Field(default=0)
    color_end: int = Field(default=0)
    color_border: int = Field(default=0)
    color: int = Field(default=0)
    id: int = Field(default=0)
    typ: int = Field(default=0)
    is_light: int = Field(default=0)
    ruid: int
    guard_level: int = Field(default=0)
    score: int = Field(default=0)
    guard_icon: str | None = Field(default=None)
    honor_icon: str | None = Field(default=None)
    v2_medal_color_start: str | None = Field(default=None)
    v2_medal_color_end: str | None = Field(default=None)
    v2_medal_color_border: str | None = Field(default=None)
    v2_medal_color_text: str | None = Field(default=None)
    v2_medal_color_level: str | None = Field(default=None)
    user_receive_count: int | None = Field(default=None)


class UserMedalWallItem(ResponseModel):
    """Source: src/user/model.rs:520:UserMedalWallItem."""

    medal_info: UserMedalInfo
    target_name: str = Field(default="")
    target_icon: str = Field(default="")
    link: str = Field(default="")
    live_status: int = Field(default=0)
    official: int | None = Field(default=None, alias="offical")
    uinfo_medal: UserMedalOwnerInfo | None = Field(default=None)


class UserMedalWall(ResponseModel):
    """Source: src/user/model.rs:492:UserMedalWall."""

    list: builtins.list[UserMedalWallItem] = Field(default_factory=list)
    count: int = Field(default=0)
    close_space_medal: int = Field(default=0)
    only_show_wearing: int = Field(default=0)
    name: str = Field(default="")
    icon: str = Field(default="")
    uid: int
    level: int = Field(default=0)


class UserNameToUidItem(ResponseModel):
    """Source: src/user/model.rs:783:UserNameToUidItem."""

    name: str
    mid: Annotated[int, BeforeValidator(_deserialize_mid_from_string_or_number)] = Field(
        alias="uid"
    )


class UserNameToUid(ResponseModel):
    """Source: src/user/model.rs:775:UserNameToUid."""

    uid_list: list[UserNameToUidItem] = Field(default_factory=list)


class UserRelationStat(ResponseModel):
    """Source: src/user/model.rs:351:UserRelationStat."""

    mid: int
    following: int
    whisper: int = Field(default=0)
    black: int = Field(default=0)
    follower: int


class UserNavStatPair(ResponseModel):
    """Source: src/user/model.rs:747:UserNavStatPair."""

    master: int = Field(default=0)
    guest: int = Field(default=0)


class UserNavStat(ResponseModel):
    """Source: src/user/model.rs:703:UserNavStat."""

    video: int = Field(default=0)
    bangumi: int = Field(default=0)
    cinema: int = Field(default=0)
    channel: UserNavStatPair = Field(
        default_factory=lambda: UserNavStatPair.model_validate({"master": 0, "guest": 0})
    )
    favourite: UserNavStatPair = Field(
        default_factory=lambda: UserNavStatPair.model_validate({"master": 0, "guest": 0})
    )
    tag: int = Field(default=0)
    article: int = Field(default=0)
    playlist: int = Field(default=0)
    album: int = Field(default=0)
    audio: int = Field(default=0)
    pugv: int = Field(default=0)
    opus: int = Field(default=0)
    season_count: int = Field(default=0, alias="season_num")


class UserVipSummary(ResponseModel):
    """Source: src/user/model.rs:192:UserVipSummary."""

    kind: int = Field(default=0, alias="type")
    status: int = Field(default=0)


class UserSpaceLiveRoom(ResponseModel):
    """Source: src/user/model.rs:203:UserSpaceLiveRoom."""

    room_status: int = Field(default=0, alias="roomStatus")
    live_status: int = Field(default=0, alias="liveStatus")
    url: str = Field(default="")
    title: str = Field(default="")
    room_id: int = Field(default=0, alias="roomid")


class UserSpaceProfile(ResponseModel):
    """Source: src/user/model.rs:133:UserSpaceProfile."""

    mid: int
    name: str
    sex: Annotated[str | None, BeforeValidator(_deserialize_optional_string)] = Field(default=None)
    face: str
    sign: str = Field(default="")
    level: int
    silence: int
    coins: float = Field(default=0.0)
    fans_badge: bool = Field(default=False)
    is_followed: bool = Field(default=False)
    top_photo: Annotated[str | None, BeforeValidator(_deserialize_optional_string)] = Field(
        default=None
    )
    official: UserOfficialSummary | None = Field(default=None)
    vip: UserVipSummary | None = Field(default=None)
    live_room: UserSpaceLiveRoom | None = Field(default=None)


class UserUploadedVideo(ResponseModel):
    """Source: src/user/model.rs:822:UserUploadedVideo."""

    aid: int
    bvid: str
    mid: int
    title: str
    author: str = Field(default="")
    pic: str = Field(default="")
    length: str = Field(default="")
    description: str = Field(default="")
    created: int = Field(default=0)
    play: int = Field(default=0)
    comment: int = Field(default=0)
    typeid: int = Field(default=0)
    video_review: int = Field(default=0)
    hide_click: bool = Field(default=False)


class UserUploadedVideoList(ResponseModel):
    """Source: src/user/model.rs:811:UserUploadedVideoList."""

    tlist: JsonValue = Field(default=None)
    videos: list[UserUploadedVideo] = Field(default_factory=list, alias="vlist")


class UserUploadedVideosPage(ResponseModel):
    """Source: src/user/model.rs:865:UserUploadedVideosPage."""

    count: int = Field(default=0)
    pn: int = Field(default=0)
    ps: int = Field(default=0)


class UserUploadedVideosButton(ResponseModel):
    """Source: src/user/model.rs:879:UserUploadedVideosButton."""

    text: str = Field(default="")
    uri: str = Field(default="")


class UserUploadedVideos(ResponseModel):
    """Source: src/user/model.rs:796:UserUploadedVideos."""

    list: UserUploadedVideoList
    page: UserUploadedVideosPage
    episodic_button: UserUploadedVideosButton | None = Field(default=None)
    is_risk: bool = Field(default=False)
