# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import TypeAdapter

from bpi._core.params import integer
from bpi.errors import InvalidParameterError
from bpi.user.models import UserSpaceNotice, UserUpStat

from .user_models import (
    UserAlbumCount,
    UserBangumiFollowList,
    UserBatchCard,
    UserBatchInfo,
    UserCardProfile,
    UserFollowers,
    UserFollowings,
    UserFollowTag,
    UserMedalWall,
    UserNameToUid,
    UserNavStat,
    UserRelationStat,
    UserSpaceProfile,
    UserUploadedVideos,
)

if TYPE_CHECKING:
    from bpi.client import AsyncBpiClient

_CARD = TypeAdapter(UserCardProfile)
_CARDS = TypeAdapter(list[UserBatchCard])
_INFOS = TypeAdapter(list[UserBatchInfo])
_ALBUM_COUNT = TypeAdapter(UserAlbumCount)
_BANGUMI_FOLLOW_LIST = TypeAdapter(UserBangumiFollowList)
_FOLLOWINGS = TypeAdapter(UserFollowings)
_FOLLOWERS = TypeAdapter(UserFollowers)
_FOLLOW_TAGS = TypeAdapter(list[UserFollowTag])
_MEDAL_WALL = TypeAdapter(UserMedalWall)
_NAME_TO_UID = TypeAdapter(UserNameToUid)
_RELATION_STAT = TypeAdapter(UserRelationStat)
_NAV_STAT = TypeAdapter(UserNavStat)
_UP_STAT = TypeAdapter(UserUpStat)
_SPACE_INFO = TypeAdapter(UserSpaceProfile)
_SPACE_NOTICE = TypeAdapter(UserSpaceNotice)
_UPLOADED_VIDEOS = TypeAdapter(UserUploadedVideos)


class UserReadMethods:
    def __init__(self, client: AsyncBpiClient) -> None:
        self._client = client

    async def card(self, *, mid: int, photo: bool | None = None) -> UserCardProfile:
        """user.card; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        if photo is not None:
            if type(photo) is not bool:
                raise InvalidParameterError("photo must be a boolean")
            params["photo"] = "true" if photo else "false"
        return await self._client._get_payload("/x/web-interface/card", params, _CARD)

    async def cards(self, *, mids: list[int]) -> list[UserBatchCard]:
        """user.cards; authenticated-read."""
        params: dict[str, str] = {}
        if not isinstance(mids, list) or not mids:
            raise InvalidParameterError("mids must be a non-empty list")
        if any(type(item) is not int or item < 1 for item in mids):
            raise InvalidParameterError("mids contains an invalid integer")
        params["uids"] = ",".join(str(item) for item in mids)
        return await self._client._get_payload(
            "/account/v1/user/cards", params, _CARDS, host="api.vc.bilibili.com"
        )

    async def infos(self, *, mids: list[int]) -> list[UserBatchInfo]:
        """user.infos; authenticated-read."""
        params: dict[str, str] = {}
        if not isinstance(mids, list) or not mids:
            raise InvalidParameterError("mids must be a non-empty list")
        if any(type(item) is not int or item < 1 for item in mids):
            raise InvalidParameterError("mids contains an invalid integer")
        params["uids"] = ",".join(str(item) for item in mids)
        return await self._client._get_payload(
            "/x/im/user_infos", params, _INFOS, host="api.vc.bilibili.com"
        )

    async def album_count(self, *, mid: int) -> UserAlbumCount:
        """user.album_count; public-read."""
        params: dict[str, str] = {}
        params["uid"] = integer(mid, "mid", 1)
        return await self._client._get_payload(
            "/link_draw/v1/doc/upload_count", params, _ALBUM_COUNT, host="api.vc.bilibili.com"
        )

    async def bangumi_follow_list(
        self, *, mid: int, kind: int = 1, page: int = 1, page_size: int = 15
    ) -> UserBangumiFollowList:
        """user.bangumi_follow_list; public-read."""
        params: dict[str, str] = {}
        params["vmid"] = integer(mid, "mid", 1)
        params["type"] = integer(kind, "kind", 1)
        if kind > 2:
            raise InvalidParameterError("kind exceeds 2")
        params["pn"] = integer(page, "page", 1)
        params["ps"] = integer(page_size, "page_size", 1)
        if page_size > 30:
            raise InvalidParameterError("page_size exceeds 30")
        return await self._client._get_payload(
            "/x/space/bangumi/follow/list", params, _BANGUMI_FOLLOW_LIST
        )

    async def followings(
        self,
        *,
        mid: int,
        order_type: str | None = None,
        page_size: int | None = None,
        page: int | None = None,
    ) -> UserFollowings:
        """user.followings; private-read."""
        params: dict[str, str] = {}
        params["vmid"] = integer(mid, "mid", 1)
        if order_type is not None:
            if not isinstance(order_type, str):
                raise InvalidParameterError("order_type must be a string")
            params["order_type"] = order_type
            params["order_type"] = order_type.strip()
            if not params["order_type"]:
                raise InvalidParameterError("order_type cannot be blank")
        if page_size is not None:
            params["ps"] = integer(page_size, "page_size", 1)
        if page is not None:
            params["pn"] = integer(page, "page", 1)
        return await self._client._get_payload("/x/relation/followings", params, _FOLLOWINGS)

    async def followers(
        self,
        *,
        mid: int,
        page_size: int | None = None,
        page: int | None = None,
        offset: str | None = None,
        last_access_ts: int | None = None,
        from_: str | None = None,
    ) -> UserFollowers:
        """user.followers; private-read."""
        params: dict[str, str] = {}
        params["vmid"] = integer(mid, "mid", 1)
        if page_size is not None:
            params["ps"] = integer(page_size, "page_size", 1)
        if page is not None:
            params["pn"] = integer(page, "page", 1)
        if offset is not None:
            if not isinstance(offset, str):
                raise InvalidParameterError("offset must be a string")
            params["offset"] = offset
            params["offset"] = offset.strip()
            if not params["offset"]:
                raise InvalidParameterError("offset cannot be blank")
        if last_access_ts is not None:
            params["last_access_ts"] = integer(last_access_ts, "last_access_ts", 0)
        if from_ is not None:
            if not isinstance(from_, str):
                raise InvalidParameterError("from_ must be a string")
            params["from"] = from_
            params["from"] = from_.strip()
            if not params["from"]:
                raise InvalidParameterError("from_ cannot be blank")
        return await self._client._get_payload("/x/relation/fans", params, _FOLLOWERS)

    async def follow_tags(self) -> list[UserFollowTag]:
        """user.follow_tags; private-read."""
        params: dict[str, str] = {}
        return await self._client._get_payload("/x/relation/tags", params, _FOLLOW_TAGS)

    async def medal_wall(self, *, target_id: int) -> UserMedalWall:
        """user.medal_wall; authenticated-read."""
        params: dict[str, str] = {}
        params["target_id"] = integer(target_id, "target_id", 1)
        return await self._client._get_payload(
            "/xlive/web-ucenter/user/MedalWall", params, _MEDAL_WALL, host="api.live.bilibili.com"
        )

    async def name_to_uid(self, *, names: list[str]) -> UserNameToUid:
        """user.name_to_uid; authenticated-read."""
        params: dict[str, str] = {}
        if not isinstance(names, list) or not names:
            raise InvalidParameterError("names must be a non-empty list")
        if any(not isinstance(item, str) or not item.strip() for item in names):
            raise InvalidParameterError("names contains a blank or invalid string")
        params["names"] = ",".join(item.strip() for item in names)
        return await self._client._get_payload(
            "/x/polymer/web-dynamic/v1/name-to-uid", params, _NAME_TO_UID
        )

    async def relation_stat(self, *, mid: int) -> UserRelationStat:
        """user.relation_stat; public-read."""
        params: dict[str, str] = {}
        params["vmid"] = integer(mid, "mid", 1)
        return await self._client._get_payload("/x/relation/stat", params, _RELATION_STAT)

    async def nav_stat(self, *, mid: int) -> UserNavStat:
        """user.nav_stat; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        return await self._client._get_payload("/x/space/navnum", params, _NAV_STAT)

    async def up_stat(self, *, mid: int) -> UserUpStat:
        """user.up_stat; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        return await self._client._get_payload("/x/space/upstat", params, _UP_STAT)

    async def space_info(self, *, mid: int) -> UserSpaceProfile:
        """user.space_info; authenticated-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        params = await self._client._sign(params)
        return await self._client._get_payload("/x/space/wbi/acc/info", params, _SPACE_INFO)

    async def space_notice(self, *, mid: int) -> UserSpaceNotice:
        """user.space_notice; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        return await self._client._get_payload("/x/space/notice", params, _SPACE_NOTICE)

    async def uploaded_videos(
        self,
        *,
        mid: int,
        order: str = "pubdate",
        tid: int = 0,
        keyword: str | None = None,
        page: int = 1,
        page_size: int = 30,
    ) -> UserUploadedVideos:
        """user.uploaded_videos; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        if not isinstance(order, str):
            raise InvalidParameterError("order must be a string")
        params["order"] = order
        if order not in ["pubdate", "click", "stow"]:
            raise InvalidParameterError("Unsupported order")
        params["tid"] = integer(tid, "tid", 0)
        if keyword is not None:
            if not isinstance(keyword, str):
                raise InvalidParameterError("keyword must be a string")
            params["keyword"] = keyword
            params["keyword"] = keyword.strip()
            if not params["keyword"]:
                raise InvalidParameterError("keyword cannot be blank")
        params["pn"] = integer(page, "page", 1)
        params["ps"] = integer(page_size, "page_size", 1)
        params = await self._client._sign(params)
        return await self._client._get_payload("/x/space/wbi/arc/search", params, _UPLOADED_VIDEOS)
