# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from pydantic import AliasChoices, Field, JsonValue

from bpi._core.response import ResponseModel
from bpi.video.models import VideoOwner, VideoStat, VideoView


class VideoTag(ResponseModel):
    """Source: src/video/tags.rs:12:VideoTag."""

    tag_id: int | None = Field(default=None)
    tag_name: str
    music_id: str | None = Field(default=None)
    tag_type: str
    jump_url: str | None = Field(default=None)


class OnlineTotalShowSwitch(ResponseModel):
    """Source: src/video/online.rs:12:OnlineTotalShowSwitch."""

    total: bool
    count: bool


class OnlineTotalResponseData(ResponseModel):
    """Source: src/video/online.rs:21:OnlineTotalResponseData."""

    total: str
    count: str
    show_switch: OnlineTotalShowSwitch


class AiSummaryPartOutline(ResponseModel):
    """Source: src/video/summary.rs:13:AiSummaryPartOutline."""

    timestamp: int
    content: str


class AiSummaryOutline(ResponseModel):
    """Source: src/video/summary.rs:22:AiSummaryOutline."""

    title: str
    part_outline: list[AiSummaryPartOutline]
    timestamp: int


class AiSummaryModelResult(ResponseModel):
    """Source: src/video/summary.rs:33:AiSummaryModelResult."""

    result_type: int
    summary: str
    outline: list[AiSummaryOutline] | None = Field(default=None)


class AiSummaryResponseData(ResponseModel):
    """Source: src/video/summary.rs:44:AiSummaryResponseData."""

    code: int
    model_result: AiSummaryModelResult | None = Field(default=None)
    stid: str | None = Field(default=None)
    status: int | None = Field(default=None)
    like_num: int
    dislike_num: int


class VideoDetailTag(ResponseModel):
    """Source: src/video/model.rs:100:VideoTag."""

    tag_id: int
    tag_name: str = Field(default="")
    jump_url: str = Field(default="")


class VideoRelated(ResponseModel):
    """Source: src/video/model.rs:113:VideoRelated."""

    aid: int
    bvid: str
    title: str = Field(default="")
    cid: int | None = Field(default=None)
    owner: VideoOwner | None = Field(default=None)
    stat: VideoStat | None = Field(default=None)


class VideoDetail(ResponseModel):
    """Source: src/video/model.rs:31:VideoDetail."""

    view: VideoView = Field(alias="View")
    tags: list[VideoDetailTag] = Field(default_factory=list, alias="Tags")
    related: list[VideoRelated] = Field(default_factory=list, alias="Related")
    card: JsonValue | None = Field(default=None, alias="Card")
    reply: JsonValue | None = Field(default=None, alias="Reply")


class Rights(ResponseModel):
    """Source: src/video/recommend.rs:64:Rights."""

    bp: int
    elec: int
    download: int
    movie: int
    pay: int
    hd5: int
    no_reprint: int
    autoplay: int
    ugc_pay: int
    is_cooperation: int
    ugc_pay_preview: int
    no_background: int


class Owner(ResponseModel):
    """Source: src/video/recommend.rs:15:Owner."""

    mid: int
    name: str
    face: str


class Stat(ResponseModel):
    """Source: src/video/recommend.rs:26:Stat."""

    view: int
    aid: int
    danmaku: int
    reply: int
    favorite: int
    coin: int
    share: int
    now_rank: int
    his_rank: int
    like: int
    dislike: int


class Dimension(ResponseModel):
    """Source: src/video/recommend.rs:81:Dimension."""

    width: int
    height: int
    rotate: int


class RelatedVideo(ResponseModel):
    """Source: src/video/recommend.rs:89:RelatedVideo."""

    aid: int
    videos: int
    tid: int
    tname: str
    copyright: int
    pic: str
    title: str
    pubdate: int
    ctime: int
    desc: str
    state: int
    duration: int
    rights: Rights
    owner: Owner
    stat: Stat
    dynamic: str
    cid: int
    dimension: Dimension
    bvid: str
    short_link_v2: str = Field(default="")


class InteractiveVideoStory(ResponseModel):
    """Source: src/video/interact_video.rs:42:InteractiveVideoStory."""

    node_id: int
    edge_id: int
    title: str
    cid: int
    start_pos: int
    cover: str
    is_current: int = Field(default=0)
    cursor: int


class InteractiveVideoDimension(ResponseModel):
    """Source: src/video/interact_video.rs:76:InteractiveVideoDimension."""

    width: int
    height: int
    rotate: int
    sar: str


class InteractiveVideoChoice(ResponseModel):
    """Source: src/video/interact_video.rs:109:InteractiveVideoChoice."""

    id: int
    platform_action: str
    native_action: str
    condition: str
    cid: int
    option: str
    is_default: int | None = Field(default=None)
    is_hidden: int | None = Field(default=None)


class InteractiveVideoQuestion(ResponseModel):
    """Source: src/video/interact_video.rs:89:InteractiveVideoQuestion."""

    id: int
    question_type: int = Field(alias="type")
    start_time_r: int
    duration: int
    pause_video: int
    title: str
    choices: list[InteractiveVideoChoice]


class InteractiveVideoEdges(ResponseModel):
    """Source: src/video/interact_video.rs:64:InteractiveVideoEdges."""

    dimension: InteractiveVideoDimension | None = Field(default=None)
    questions: list[InteractiveVideoQuestion] = Field(default_factory=list)
    skin: JsonValue | None = Field(default=None)


class InteractiveVideoPreloadVideo(ResponseModel):
    """Source: src/video/interact_video.rs:140:InteractiveVideoPreloadVideo."""

    aid: int
    cid: int


class InteractiveVideoPreload(ResponseModel):
    """Source: src/video/interact_video.rs:132:InteractiveVideoPreload."""

    video: list[InteractiveVideoPreloadVideo] = Field(default_factory=list)


class InteractiveVideoHiddenVar(ResponseModel):
    """Source: src/video/interact_video.rs:149:InteractiveVideoHiddenVar."""

    value: int
    id: str
    id_v2: str
    var_type: int = Field(alias="type")
    is_show: int
    name: str


class InteractiveVideoInfoResponseData(ResponseModel):
    """Source: src/video/interact_video.rs:12:InteractiveVideoInfoResponseData."""

    title: str
    edge_id: int
    story_list: list[InteractiveVideoStory] = Field(default_factory=list)
    edges: InteractiveVideoEdges | None = Field(default=None)
    preload: InteractiveVideoPreload | None = Field(default=None)
    hidden_vars: list[InteractiveVideoHiddenVar] = Field(default_factory=list)
    is_leaf: int
    no_tutorial: int = Field(default=0)
    no_backtracking: int = Field(default=0)
    no_evaluation: int = Field(default=0)


class SeriesMeta(ResponseModel):
    """Source: src/video/collection/info.rs:127:SeriesMeta."""

    category: int
    creator: str
    ctime: int
    description: str
    keywords: list[str]
    last_update_ts: int
    mid: int
    mtime: int
    name: str
    raw_keywords: str
    series_id: int
    state: int
    total: int
    cover: str | None = Field(default=None)


class GetSeriesData(ResponseModel):
    """Source: src/video/collection/info.rs:184:GetSeriesData."""

    meta: SeriesMeta
    recent_aids: list[int]


class PageInfo(ResponseModel):
    """Source: src/video/collection/info.rs:59:PageInfo."""

    page_num: int = Field(validation_alias=AliasChoices("page_num", "num"))
    page_size: int = Field(validation_alias=AliasChoices("page_size", "size"))
    total: int


class ArchiveStat(ResponseModel):
    """Source: src/video/collection/info.rs:17:ArchiveStat."""

    view: int
    vt: int | None = Field(default=None)


class Archive(ResponseModel):
    """Source: src/video/collection/info.rs:26:Archive."""

    aid: int
    bvid: str
    ctime: int
    duration: int
    interactive_video: bool
    pic: str
    playback_position: int
    pubdate: int
    stat: ArchiveStat
    state: int
    title: str
    ugc_pay: int
    vt_display: str
    is_lesson_video: int | None = Field(default=None)


class GetSeriesArchivesData(ResponseModel):
    """Source: src/video/collection/info.rs:193:GetSeriesArchivesData."""

    aids: list[int]
    page: PageInfo
    archives: list[Archive]


class SeasonsArchivesMeta(ResponseModel):
    """Source: src/video/collection/info.rs:72:SeasonsArchivesMeta."""

    category: int
    cover: str
    description: str
    mid: int
    name: str
    ptime: int
    season_id: int
    total: int


class GetSeasonsArchivesData(ResponseModel):
    """Source: src/video/collection/info.rs:93:GetSeasonsArchivesData."""

    aids: list[int]
    archives: list[Archive]
    meta: SeasonsArchivesMeta
    page: PageInfo


class SeasonsMeta(ResponseModel):
    """Source: src/video/collection/info.rs:106:SeasonsMeta."""

    category: int
    cover: str
    description: str
    mid: int
    name: str
    ptime: int
    season_id: int
    total: int


class SeasonsItem(ResponseModel):
    """Source: src/video/collection/info.rs:145:SeasonsItem."""

    archives: list[Archive]
    meta: SeasonsMeta
    recent_aids: list[int]


class SeriesItem(ResponseModel):
    """Source: src/video/collection/info.rs:155:SeriesItem."""

    archives: list[Archive]
    meta: SeriesMeta
    recent_aids: list[int]


class ItemsList(ResponseModel):
    """Source: src/video/collection/info.rs:166:ItemsList."""

    page: PageInfo
    seasons_list: list[SeasonsItem]
    series_list: list[SeriesItem]


class GetSeasonsSeriesData(ResponseModel):
    """Source: src/video/collection/info.rs:177:GetSeasonsSeriesData."""

    items_lists: ItemsList


class DmMaskInfo(ResponseModel):
    """Source: src/video/player.rs:80:DmMaskInfo."""

    cid: int
    plat: int
    fps: int
    time: int
    mask_url: str


class SubtitleItem(ResponseModel):
    """Source: src/video/player.rs:103:SubtitleItem."""

    ai_status: int
    ai_type: int
    id: int
    id_str: str
    is_lock: bool
    lan: str
    lan_doc: str
    subtitle_url: str
    subtitle_type: int = Field(alias="type")


class SubtitleInfo(ResponseModel):
    """Source: src/video/player.rs:93:SubtitleInfo."""

    allow_submit: bool
    lan: str
    lan_doc: str
    subtitles: list[SubtitleItem] = Field(default_factory=list)


class ViewPoint(ResponseModel):
    """Source: src/video/player.rs:121:ViewPoint."""

    content: str
    from_: int = Field(alias="from")
    to: int
    point_type: int = Field(alias="type")
    img_url: str = Field(alias="imgUrl")
    logo_url: str = Field(alias="logoUrl")
    team_type: str
    team_name: str


class InteractionInfo(ResponseModel):
    """Source: src/video/player.rs:141:InteractionInfo."""

    graph_version: int
    msg: str | None = Field(default=None)
    error_toast: str | None = Field(default=None)
    mark: int | None = Field(default=None)
    need_reload: int | None = Field(default=None)


class PlayerOptions(ResponseModel):
    """Source: src/video/player.rs:154:PlayerOptions."""

    is_360: bool
    without_vip: bool


class BgmInfo(ResponseModel):
    """Source: src/video/player.rs:162:BgmInfo."""

    music_id: str
    music_title: str
    jump_url: str


class ElecHighLevel(ResponseModel):
    """Source: src/video/player.rs:173:ElecHighLevel."""

    privilege_type: int
    title: str
    sub_title: str
    show_button: bool
    button_text: str
    jump_url: JsonValue | None = Field(default=None)
    intro: str
    open: bool = Field(default=False)
    new: bool = Field(default=False)
    question_text: str = Field(default="")
    qa_detail_link: str = Field(default="")


class PlayerInfoResponseData(ResponseModel):
    """Source: src/video/player.rs:12:PlayerInfoResponseData."""

    aid: int
    bvid: str
    allow_bp: bool
    no_share: bool
    cid: int
    dm_mask: DmMaskInfo | None = Field(default=None)
    subtitle: SubtitleInfo | None = Field(default=None)
    view_points: list[ViewPoint] = Field(default_factory=list)
    ip_info: JsonValue | None = Field(default=None)
    login_mid: int
    login_mid_hash: str | None = Field(default=None)
    is_owner: bool
    name: str
    permission: str
    level_info: JsonValue | None = Field(default=None)
    vip: JsonValue | None = Field(default=None)
    answer_status: int
    block_time: int
    role: str
    last_play_time: int
    last_play_cid: int
    now_time: int
    online_count: int | None = Field(default=None)
    need_login_subtitle: bool
    preview_toast: str
    interaction: InteractionInfo | None = Field(default=None)
    options: PlayerOptions | None = Field(default=None)
    guide_attention: JsonValue | None = Field(default=None)
    jump_card: JsonValue | None = Field(default=None)
    operation_card: JsonValue | None = Field(default=None)
    online_switch: JsonValue | None = Field(default=None)
    fawkes: JsonValue | None = Field(default=None)
    show_switch: JsonValue | None = Field(default=None)
    bgm_info: BgmInfo | None = Field(default=None)
    toast_block: bool
    is_upower_exclusive: bool
    is_upower_play: bool
    is_ugc_pay_preview: bool
    elec_high_level: ElecHighLevel | None = Field(default=None)
    disable_show_up_info: bool


class RcmdReason(ResponseModel):
    """Source: src/video/recommend.rs:115:RcmdReason."""

    reason_type: int = Field(alias="reason_type")
    content: str | None = Field(default=None)


class HomeRmdStat(ResponseModel):
    """Source: src/video/recommend.rs:53:HomeRmdStat."""

    view: int
    danmaku: int
    like: int


class RcmdItem(ResponseModel):
    """Source: src/video/recommend.rs:125:RcmdItem."""

    av_feature: JsonValue | None = Field(default=None)
    business_info: JsonValue | None = Field(default=None)
    bvid: str
    cid: int
    duration: int
    goto: str
    id: int
    is_followed: int
    is_stock: int
    owner: Owner
    pic: str
    pos: int
    pubdate: int
    rcmd_reason: RcmdReason | None = Field(default=None)
    room_info: JsonValue | None = Field(default=None)
    show_info: int
    stat: HomeRmdStat | None = Field(default=None)
    title: str
    track_id: str
    uri: str


class RcmdFeedResponseData(ResponseModel):
    """Source: src/video/recommend.rs:165:RcmdFeedResponseData."""

    item: list[RcmdItem]
    mid: int
    preload_expose_pct: float
    preload_floor_expose_pct: float
