# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.
from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import ConfigDict, TypeAdapter

from bpi._core.params import integer, video_id
from bpi.errors import InvalidParameterError

from .video_models import (
    AiSummaryResponseData,
    GetSeasonsArchivesData,
    GetSeasonsSeriesData,
    GetSeriesArchivesData,
    GetSeriesData,
    InteractiveVideoInfoResponseData,
    OnlineTotalResponseData,
    PlayerInfoResponseData,
    RcmdFeedResponseData,
    RelatedVideo,
    VideoDetail,
    VideoTag,
)

if TYPE_CHECKING:
    from bpi.client import AsyncBpiClient

_DESC = TypeAdapter(str, config=ConfigDict(strict=True))
_TAGS = TypeAdapter(list[VideoTag])
_ONLINE_TOTAL = TypeAdapter(OnlineTotalResponseData)
_AI_SUMMARY = TypeAdapter(AiSummaryResponseData)
_DETAIL = TypeAdapter(VideoDetail)
_RELATED_VIDEOS = TypeAdapter(list[RelatedVideo])
_INTERACTIVE_VIDEO_INFO = TypeAdapter(InteractiveVideoInfoResponseData)
_SERIES_INFO = TypeAdapter(GetSeriesData)
_SERIES_ARCHIVES = TypeAdapter(GetSeriesArchivesData)
_SEASONS_ARCHIVES_LIST = TypeAdapter(GetSeasonsArchivesData)
_HOME_SEASONS_SERIES = TypeAdapter(GetSeasonsSeriesData)
_SEASONS_SERIES_LIST = TypeAdapter(GetSeasonsSeriesData)
_PLAYER_INFO_V2 = TypeAdapter(PlayerInfoResponseData)
_HOMEPAGE_RECOMMENDATIONS = TypeAdapter(RcmdFeedResponseData)


class VideoReadMethods:
    def __init__(self, client: AsyncBpiClient) -> None:
        self._client = client

    async def desc(self, *, aid: int | None = None, bvid: str | None = None) -> str:
        """video.desc; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        return await self._client._get_payload("/x/web-interface/archive/desc", params, _DESC)

    async def tags(
        self, *, aid: int | None = None, bvid: str | None = None, cid: int | None = None
    ) -> list[VideoTag]:
        """video.tags; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        if cid is not None:
            params["cid"] = integer(cid, "cid", 1)
        return await self._client._get_payload("/x/web-interface/view/detail/tag", params, _TAGS)

    async def online_total(
        self, *, aid: int | None = None, bvid: str | None = None, cid: int
    ) -> OnlineTotalResponseData:
        """video.online_total; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        params["cid"] = integer(cid, "cid", 1)
        return await self._client._get_payload("/x/player/online/total", params, _ONLINE_TOTAL)

    async def ai_summary(
        self, *, aid: int | None = None, bvid: str | None = None, cid: int, up_mid: int
    ) -> AiSummaryResponseData:
        """video.ai_summary; authenticated-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        params["cid"] = integer(cid, "cid", 1)
        params["up_mid"] = integer(up_mid, "up_mid", 1)
        params = await self._client._sign(params)
        return await self._client._get_payload(
            "/x/web-interface/view/conclusion/get", params, _AI_SUMMARY
        )

    async def detail(
        self, *, aid: int | None = None, bvid: str | None = None, need_elec: bool | None = None
    ) -> VideoDetail:
        """video.detail; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        if need_elec is not None:
            if type(need_elec) is not bool:
                raise InvalidParameterError("need_elec must be a boolean")
            params["need_elec"] = "1" if need_elec else "0"
        return await self._client._get_payload("/x/web-interface/view/detail", params, _DETAIL)

    async def related_videos(
        self, *, aid: int | None = None, bvid: str | None = None
    ) -> list[RelatedVideo]:
        """video.related_videos; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        return await self._client._get_payload(
            "/x/web-interface/archive/related", params, _RELATED_VIDEOS
        )

    async def interactive_video_info(
        self,
        *,
        aid: int | None = None,
        bvid: str | None = None,
        graph_version: int,
        edge_id: int | None = None,
    ) -> InteractiveVideoInfoResponseData:
        """video.interactive_video_info; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        params["graph_version"] = integer(graph_version, "graph_version", 1)
        if edge_id is not None:
            params["edge_id"] = integer(edge_id, "edge_id", 1)
        return await self._client._get_payload(
            "/x/stein/edgeinfo_v2", params, _INTERACTIVE_VIDEO_INFO
        )

    async def series_info(self, *, series_id: int) -> GetSeriesData:
        """video.collection.series_info; public-read."""
        params: dict[str, str] = {}
        params["series_id"] = integer(series_id, "series_id", 1)
        return await self._client._get_payload("/x/series/series", params, _SERIES_INFO)

    async def series_archives(
        self,
        *,
        mid: int,
        series_id: int,
        only_normal: bool | None = None,
        sort: str | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
    ) -> GetSeriesArchivesData:
        """video.collection.series_archives; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        params["series_id"] = integer(series_id, "series_id", 1)
        if only_normal is not None:
            if type(only_normal) is not bool:
                raise InvalidParameterError("only_normal must be a boolean")
            params["only_normal"] = "true" if only_normal else "false"
        if sort is not None:
            if not isinstance(sort, str):
                raise InvalidParameterError("sort must be a string")
            params["sort"] = sort
            if sort not in ["asc", "desc"]:
                raise InvalidParameterError("Unsupported sort")
        if page_num is not None:
            params["pn"] = integer(page_num, "page_num", 1)
        if page_size is not None:
            params["ps"] = integer(page_size, "page_size", 1)
        return await self._client._get_payload("/x/series/archives", params, _SERIES_ARCHIVES)

    async def seasons_archives_list(
        self,
        *,
        mid: int,
        season_id: int,
        page_num: int = 1,
        page_size: int = 20,
        sort_reverse: bool | None = None,
    ) -> GetSeasonsArchivesData:
        """video.collection.seasons_archives_list; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        params["season_id"] = integer(season_id, "season_id", 1)
        params["page_num"] = integer(page_num, "page_num", 1)
        params["page_size"] = integer(page_size, "page_size", 1)
        if sort_reverse is not None:
            if type(sort_reverse) is not bool:
                raise InvalidParameterError("sort_reverse must be a boolean")
            params["sort_reverse"] = "true" if sort_reverse else "false"
        params = await self._client._sign(params)
        return await self._client._get_payload(
            "/x/polymer/web-space/seasons_archives_list", params, _SEASONS_ARCHIVES_LIST
        )

    async def home_seasons_series(
        self, *, mid: int, page_num: int = 1, page_size: int = 10
    ) -> GetSeasonsSeriesData:
        """video.collection.home_seasons_series; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        params["page_num"] = integer(page_num, "page_num", 1)
        params["page_size"] = integer(page_size, "page_size", 1)
        params = await self._client._sign(params)
        return await self._client._get_payload(
            "/x/polymer/web-space/home/seasons_series", params, _HOME_SEASONS_SERIES
        )

    async def seasons_series_list(
        self, *, mid: int, page_num: int | None = None, page_size: int | None = None
    ) -> GetSeasonsSeriesData:
        """video.collection.seasons_series_list; public-read."""
        params: dict[str, str] = {}
        params["mid"] = integer(mid, "mid", 1)
        if page_num is not None:
            params["page_num"] = integer(page_num, "page_num", 1)
        if page_size is not None:
            params["page_size"] = integer(page_size, "page_size", 1)
        params = await self._client._sign(params)
        return await self._client._get_payload(
            "/x/polymer/web-space/seasons_series_list", params, _SEASONS_SERIES_LIST
        )

    async def player_info_v2(
        self,
        *,
        aid: int | None = None,
        bvid: str | None = None,
        cid: int,
        season_id: int | None = None,
        ep_id: int | None = None,
    ) -> PlayerInfoResponseData:
        """video.player_info_v2; public-read."""
        params: dict[str, str] = {}
        params.update(video_id(aid, bvid))
        params["cid"] = integer(cid, "cid", 1)
        if season_id is not None:
            params["season_id"] = integer(season_id, "season_id", 1)
        if ep_id is not None:
            params["ep_id"] = integer(ep_id, "ep_id", 1)
        params = await self._client._sign(params)
        return await self._client._get_payload("/x/player/wbi/v2", params, _PLAYER_INFO_V2)

    async def homepage_recommendations(
        self, *, page_size: int = 12, fresh_idx: int = 1, fetch_row: int = 1
    ) -> RcmdFeedResponseData:
        """video.homepage_recommendations; public-read."""
        params: dict[str, str] = {"fresh_type": "4"}
        params["ps"] = integer(page_size, "page_size", 1)
        if page_size > 30:
            raise InvalidParameterError("page_size exceeds 30")
        params["fresh_idx"] = integer(fresh_idx, "fresh_idx", 1)
        params["fetch_row"] = integer(fetch_row, "fetch_row", 1)
        params["fresh_idx_1h"] = params["fresh_idx"]
        params["brush"] = params["fresh_idx"]
        params = await self._client._sign(params)
        return await self._client._get_payload(
            "/x/web-interface/wbi/index/top/feed/rcmd", params, _HOMEPAGE_RECOMMENDATIONS
        )
