"""Generate a reviewed batch of simple GET methods and models from the AST inventory."""

from __future__ import annotations

import argparse
import ast
import json
import keyword
import re
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

Record = dict[str, Any]
OLD_HEADER = (
    "# Generated by tools.migration.generate; edit migration/batch-3.json or the generator.\n"
)
HEADER = "# Generated by tools.migration.generate; edit migration/batch-*.json or the generator.\n"
SCALARS = {
    "String": "str",
    "bool": "bool",
    "f32": "float",
    "f64": "float",
    "serde_json::Value": "JsonValue",
    "Aid": "int",
    "Cid": "int",
    "Mid": "int",
    "MediaId": "int",
    "Bvid": "str",
}


class ModelEmitter:
    def __init__(
        self,
        inventory: Record,
        domain: str,
        defaults: Record,
        names: Record | None = None,
        external: Record | None = None,
        external_types: Record | None = None,
    ) -> None:
        self.domain = domain
        self.types = [t for t in inventory["types"] if t["domain"] == domain]
        self.defaults = defaults
        self.emitted: dict[str, str] = {}
        self.origins: dict[str, str] = {}
        self.visiting: set[str] = set()
        self.names = names or {}
        self.external = external or {}
        self.external_types = external_types or {}
        self.external_imports: set[str] = set()
        self.serde_helpers: set[str] = set()
        self.needs_builtins = False

    def external_model(self, reference: str, origin: str) -> str:
        module, name = reference.split(":")
        if not all(part.isidentifier() for part in module.split(".")) or not name.isidentifier():
            raise ValueError("Invalid external model reference")
        if name in self.origins and self.origins[name] != origin:
            raise ValueError(f"Python model name collision: {name}")
        self.origins[name] = origin
        self.external_imports.add(f"from {module} import {name}")
        return name

    def convert(self, rust: str, source: str) -> str:
        if rust in SCALARS:
            return SCALARS[rust]
        if re.fullmatch(r"[ui](8|16|32|64|128|size)", rust):
            return "int"
        for prefix, template in (("Vec<", "list[{}]"), ("Option<", "{} | None")):
            if rust.startswith(prefix) and rust.endswith(">"):
                return template.format(self.convert(rust[len(prefix) : -1], source))
        if mapping := re.fullmatch(r"(?:std::collections::)?HashMap<String,\s*(.+)>", rust):
            return f"dict[str, {self.convert(mapping.group(1), source)}]"
        external_type = self.external_types.get(f"{self.domain}:{rust}")
        if external_type is not None:
            return self.external_model(str(external_type), f"{self.domain}:{rust}")
        candidates = [t for t in self.types if t["name"] == rust]
        local = [t for t in candidates if t["source"]["path"] == source]
        candidates = local or candidates
        if len(candidates) != 1:
            raise ValueError(f"Ambiguous or unsupported type {rust} in {source}")
        model = candidates[0]
        origin = model["id"]
        qualified = f"{model['source']['path']}:{rust}"
        if qualified in self.external:
            return self.external_model(str(self.external[qualified]), origin)
        rust_name = rust
        rust = self.names.get(qualified, rust)
        if not rust.isidentifier() or keyword.iskeyword(rust):
            raise ValueError("Invalid Python model name")
        if rust in self.origins and self.origins[rust] != origin:
            raise ValueError(f"Python model name collision: {rust}")
        self.origins[rust] = origin
        if rust in self.emitted:
            return rust
        if rust in self.visiting:
            raise ValueError(f"Recursive model requires manual handling: {rust}")
        if model["kind"] != "struct_item":
            raise ValueError(f"Unsupported model attributes/kind: {origin}")
        serde_attributes = [a for a in model["attributes"] if "serde(" in a]
        struct_default = serde_attributes == ["#[serde(default)]"]
        if serde_attributes and not struct_default:
            raise ValueError(f"Unsupported model attributes/kind: {origin}")
        if struct_default and not any(
            "derive(" in a and "Default" in a for a in model["attributes"]
        ):
            raise ValueError(f"serde(default) requires a Default model: {origin}")
        self.visiting.add(rust)
        lines = [f"class {rust}(ResponseModel):", f'    """Source: {origin}."""']
        for field in model["fields"]:
            lines.append(
                self.field(
                    rust_name,
                    field,
                    model["source"]["path"],
                    struct_default=struct_default,
                )
            )
        if not model["fields"]:
            raise ValueError(f"Empty or tuple struct needs manual handling: {origin}")
        self.emitted[rust] = "\n".join(lines)
        self.visiting.remove(rust)
        return rust

    def field(self, model: str, field: Record, source: str, *, struct_default: bool = False) -> str:
        raw_name = field["name"].removeprefix("r#")
        name = raw_name + "_" if keyword.iskeyword(raw_name) else raw_name
        rust_type = field["rust_type"]
        annotation = self.convert(rust_type, source)
        if raw_name == "list" and annotation.startswith("list["):
            self.needs_builtins = True
            annotation = "builtins.list[" + annotation[len("list[") :]
        alias = raw_name if name != raw_name else None
        aliases: list[str] = []
        default = None
        has_default = False
        deserialize_with: str | None = None
        for attribute in field["attributes"]:
            match = re.fullmatch(r"#\[serde\((.*)\)\]", attribute, flags=re.S)
            if not match:
                raise ValueError(f"Unsupported field attribute {model}.{name}: {attribute}")
            for entry in match.group(1).split(","):
                entry = entry.strip()
                if entry == "default":
                    has_default = True
                elif rename := re.fullmatch(r'rename\s*=\s*"([^"\\]+)"', entry):
                    alias = rename.group(1)
                elif alternative := re.fullmatch(r'alias\s*=\s*"([^"\\]+)"', entry):
                    aliases.append(alternative.group(1))
                elif custom := re.fullmatch(r'deserialize_with\s*=\s*"([^"\\]+)"', entry):
                    deserialize_with = custom.group(1)
                else:
                    raise ValueError(f"Unsupported serde rule {model}.{name}: {entry}")
        if deserialize_with == "deserialize_mid_from_string_or_number":
            if rust_type != "Mid":
                raise ValueError(f"Unsupported serde custom deserializer type {model}.{name}")
            self.serde_helpers.add("mid")
            annotation = "Annotated[int, BeforeValidator(_deserialize_mid_from_string_or_number)]"
        elif deserialize_with == "deserialize_optional_string":
            if rust_type != "Option<String>":
                raise ValueError(f"Unsupported serde custom deserializer type {model}.{name}")
            self.serde_helpers.add("optional_string")
            annotation = "Annotated[str | None, BeforeValidator(_deserialize_optional_string)]"
        elif deserialize_with is not None:
            raise ValueError(
                f"Unsupported serde custom deserializer {model}.{name}: {deserialize_with}"
            )
        if rust_type.startswith("Option<"):
            default = "default=None"
        elif has_default or struct_default:
            override = self.defaults.get(f"{model}.{raw_name}")
            if override is not None:
                default = f"default_factory=lambda: {annotation}.model_validate({override!r})"
            elif annotation.startswith(("list[", "builtins.list[")):
                default = "default_factory=list"
            elif annotation in {"str", "int", "float", "bool", "JsonValue"}:
                default = (
                    "default="
                    + {
                        "str": "''",
                        "int": "0",
                        "float": "0.0",
                        "bool": "False",
                        "JsonValue": "None",
                    }[annotation]
                )
            else:
                raise ValueError(f"Missing reviewed default for {model}.{raw_name}")
        options = [x for x in (default, f"alias={alias!r}" if alias else None) if x]
        if aliases:
            choices = ", ".join(repr(v) for v in [alias or raw_name, *aliases])
            options.append(f"validation_alias=AliasChoices({choices})")
        suffix = f" = Field({', '.join(options)})" if options else ""
        return f"    {name}: {annotation}{suffix}"

    def render(self) -> str:
        typing_import = "from typing import Annotated\n" if self.serde_helpers else ""
        module_import = "import builtins\n" if self.needs_builtins else ""
        pydantic_imports = ["AliasChoices", "Field", "JsonValue"]
        if self.serde_helpers:
            pydantic_imports.append("BeforeValidator")
        helpers = []
        if "mid" in self.serde_helpers:
            helpers.append(
                "def _deserialize_mid_from_string_or_number(value: object) -> object:\n"
                "    if type(value) is int:\n"
                "        if value > 0:\n"
                "            return value\n"
                "        raise ValueError('mid must be positive')\n"
                "    if isinstance(value, str):\n"
                "        try:\n"
                "            parsed = int(value)\n"
                "        except ValueError:\n"
                "            raise ValueError('mid must be a string or number') from None\n"
                "        if parsed > 0:\n"
                "            return parsed\n"
                "    raise ValueError('mid must be a string or number')"
            )
        if "optional_string" in self.serde_helpers:
            helpers.append(
                "def _deserialize_optional_string(value: object) -> object:\n"
                "    if isinstance(value, str) and not value.strip():\n"
                "        return None\n"
                "    return value"
            )
        helper_source = "\n\n\n".join(helpers)
        if helper_source:
            helper_source += "\n\n\n"
        return HEADER + (
            "from __future__ import annotations\n\n"
            + module_import
            + typing_import
            + f"from pydantic import {', '.join(pydantic_imports)}\n"
            "from bpi._core.response import ResponseModel\n\n\n"
            + helper_source
            + "\n".join(sorted(self.external_imports))
            + "\n\n"
            + "\n\n\n".join(self.emitted.values())
            + "\n"
        )


def format_python(content: str) -> str:
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "--fix",
            "--select",
            "I,F401",
            "--stdin-filename",
            "generated.py",
            "-",
        ],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", "generated.py", "-"],
        input=result.stdout,
        text=True,
        capture_output=True,
        check=True,
    )
    ast.parse(result.stdout)
    return result.stdout


def render(inventory: Record, spec: Record) -> dict[str, str]:
    if inventory["baseline"]["commit"] != spec["source_commit"]:
        raise ValueError("Source commit differs from the reviewed batch")
    outputs = {}
    manifest: Record = {"source_commit": spec["source_commit"], "apis": [], "cases": []}
    for domain in sorted({e["domain"] for e in spec["endpoints"]}):
        if not domain.isidentifier():
            raise ValueError("Invalid domain")
        emitter = ModelEmitter(
            inventory,
            domain,
            spec.get("model_defaults", {}),
            spec.get("model_names"),
            spec.get("external_models"),
            spec.get("external_types"),
        )
        methods: list[str] = []
        adapters: list[str] = []
        imports: set[str] = set()
        client_external_imports: set[str] = set()
        seen = set()
        for endpoint in (e for e in spec["endpoints"] if e["domain"] == domain):
            name = endpoint["method"]
            if not name.isidentifier() or keyword.iskeyword(name) or name in seen:
                raise ValueError(f"Invalid or duplicate method: {name}")
            seen.add(name)
            matches = [
                m
                for m in inventory["methods"]
                if m["domain"] == domain
                and m["name"] == name
                and endpoint["contract"] in m["contract_labels"]
            ]
            if len(matches) != 1 or matches[0]["automation"] != "request_shell_candidate":
                raise ValueError(f"Method is not a unique reviewed request candidate: {name}")
            method = matches[0]
            optional_payload = endpoint.get("optional_payload", False)
            if type(optional_payload) is not bool:
                raise ValueError("Optional payload must be a boolean")
            helper = "send_bpi_optional_payload" if optional_payload else "send_bpi_payload"
            if helper not in method["calls"]:
                raise ValueError("Reviewed payload mode does not match the source helper")
            contract = next(c for c in inventory["contracts"] if c["id"] == endpoint["contract"])
            url = urlsplit(contract["request"]["url"])
            if contract["risk"] not in {"public-read", "authenticated-read", "private-read"}:
                raise ValueError("Only read contracts are supported")
            allowed_hosts = {
                "api.bilibili.com",
                "www.bilibili.com",
                "api.vc.bilibili.com",
                "api.live.bilibili.com",
            }
            if (
                contract["request"]["method"] != "GET"
                or url.scheme != "https"
                or url.netloc not in allowed_hosts
                or url.netloc != endpoint.get("host", "api.bilibili.com")
                or url.query
                or url.fragment
            ):
                raise ValueError("Only reviewed Bilibili host GET requests are supported")
            csrf = endpoint.get("csrf")
            if csrf not in (None, "optional") or ("csrf" in method["calls"]) != (csrf is not None):
                raise ValueError("CSRF mode must explicitly match the source helper")
            if method["signing_evidence"] not in (
                [],
                ["get_wbi_sign2"],
                ["sign_wbi_params"],
            ):
                raise ValueError("Unknown signing helper")
            rust_return = method["return_type"]
            if not rust_return.startswith("BpiResult<") or not rust_return.endswith(">"):
                raise ValueError("Unsupported return envelope")
            annotation = emitter.convert(rust_return[10:-1], endpoint["models_file"])
            if optional_payload and not rust_return.startswith("BpiResult<Option<"):
                raise ValueError("Optional payload requires an Option return type")
            imports.update(emitter.emitted)
            direct_external = next(
                (
                    statement
                    for statement in emitter.external_imports
                    if statement.endswith(f" import {annotation}")
                ),
                None,
            )
            if direct_external is not None:
                client_external_imports.add(direct_external)
            elif annotation.isidentifier() and annotation not in {"int", "str", "bool", "float"}:
                imports.add(annotation)
            adapter = f"_{name.upper()}"
            config = (
                ", config=ConfigDict(strict=True)" if annotation in {"int", "str", "bool"} else ""
            )
            adapter_type = f": TypeAdapter[{annotation}]" if optional_payload else ""
            adapters.append(f"{adapter}{adapter_type} = TypeAdapter({annotation}{config})")
            parameters = []
            fixed = endpoint.get("fixed_query", {})
            if not all(isinstance(k, str) and isinstance(v, str) for k, v in fixed.items()):
                raise ValueError("Fixed query must contain strings")
            body = [f"        params: dict[str, str] = {fixed!r}"]
            if endpoint.get("video_id"):
                parameters.extend(["aid: int | None = None", "bvid: str | None = None"])
                body.append("        params.update(video_id(aid, bvid))")
            for param in endpoint["params"]:
                key = param["name"]
                if not key.isidentifier() or keyword.iskeyword(key):
                    raise ValueError("Invalid parameter name")
                kind = param.get("kind", "int")
                annotations = {
                    "int": "int",
                    "bool": "bool",
                    "str": "str",
                    "int_list": "list[int]",
                    "str_list": "list[str]",
                }
                if kind not in annotations:
                    raise ValueError("Unsupported parameter kind")
                wire = param.get("wire", key)
                if not wire.isidentifier():
                    raise ValueError("Invalid wire parameter name")
                declaration = f"{key}: {annotations[kind]}"
                if param.get("optional"):
                    declaration += " | None = None"
                elif "default" in param:
                    expected = {"int": int, "bool": bool, "str": str}.get(kind)
                    if expected is None or type(param["default"]) is not expected:
                        raise ValueError("Default does not match parameter kind")
                    declaration += f" = {param['default']!r}"
                parameters.append(declaration)
                indent = "        "
                if param.get("optional"):
                    body.append(f"        if {key} is not None:")
                    indent += "    "
                if kind == "int":
                    body.append(
                        f"{indent}params[{wire!r}] = integer({key}, {key!r}, {param['min']})"
                    )
                elif kind == "bool":
                    encoding = param.get("encoding")
                    if encoding not in {"01", "truefalse"}:
                        raise ValueError("Boolean encoding must be explicit")
                    body.extend(
                        [
                            f"{indent}if type({key}) is not bool:",
                            f"{indent}    raise InvalidParameterError('{key} must be a boolean')",
                        ]
                    )
                    true, false = ("1", "0") if encoding == "01" else ("true", "false")
                    body.append(f"{indent}params[{wire!r}] = {true!r} if {key} else {false!r}")
                elif kind == "str":
                    body.extend(
                        [
                            f"{indent}if not isinstance({key}, str):",
                            f"{indent}    raise InvalidParameterError('{key} must be a string')",
                            f"{indent}params[{wire!r}] = {key}",
                        ]
                    )
                    if param.get("nonblank"):
                        body.extend(
                            [
                                f"{indent}params[{wire!r}] = {key}.strip()",
                                f"{indent}if not params[{wire!r}]:",
                                f"{indent}    raise InvalidParameterError('{key} cannot be blank')",
                            ]
                        )
                elif kind == "int_list":
                    if param.get("encoding") != "csv":
                        raise ValueError("Integer list encoding must be csv")
                    body.extend(
                        [
                            f"{indent}if not isinstance({key}, list) or not {key}:",
                            f"{indent}    raise InvalidParameterError("
                            f"'{key} must be a non-empty list')",
                            f"{indent}if any(type(item) is not int "
                            f"or item < {param['min']} for item in {key}):",
                            f"{indent}    raise InvalidParameterError("
                            f"'{key} contains an invalid integer')",
                            f"{indent}params[{wire!r}] = ','.join(str(item) for item in {key})",
                        ]
                    )
                else:
                    if param.get("encoding") != "csv":
                        raise ValueError("String list encoding must be csv")
                    body.extend(
                        [
                            f"{indent}if not isinstance({key}, list) or not {key}:",
                            f"{indent}    raise InvalidParameterError("
                            f"'{key} must be a non-empty list')",
                            f"{indent}if any(not isinstance(item, str) "
                            f"or not item.strip() for item in {key}):",
                            f"{indent}    raise InvalidParameterError("
                            f"'{key} contains a blank or invalid string')",
                            f"{indent}params[{wire!r}] = ','.join(item.strip() for item in {key})",
                        ]
                    )
                if "max" in param:
                    body.extend(
                        [
                            f"{indent}if {key} > {param['max']}:",
                            f"{indent}    raise InvalidParameterError("
                            f"'{key} exceeds {param['max']}')",
                        ]
                    )
                if "choices" in param:
                    body.extend(
                        [
                            f"{indent}if {key} not in {param['choices']!r}:",
                            f"{indent}    raise InvalidParameterError('Unsupported {key}')",
                        ]
                    )
            for target, source in endpoint.get("query_copies", {}).items():
                if source not in {p.get("wire", p["name"]) for p in endpoint["params"]}:
                    raise ValueError("Query copy must reference a declared parameter")
                body.append(f"        params[{target!r}] = params[{source!r}]")
            if method["signing_evidence"]:
                body.append("        params = await self._client._sign(params)")
            if csrf == "optional":
                body.append(
                    "        params['csrf'] = self._client._csrf("
                    f"host={url.netloc!r}, optional=True)"
                )
            options = ""
            if url.netloc != "api.bilibili.com":
                options += f", host={url.netloc!r}"
            if optional_payload:
                options += ", optional=True"
            body.append(
                "        return await self._client._get_payload("
                f"{url.path!r}, params, {adapter}{options})"
            )
            args = ", *, " + ", ".join(parameters) if parameters else ""
            methods.append(
                f"    async def {name}(self{args}) -> {annotation}:\n"
                f'        """{contract["id"]}; {contract["risk"]}."""\n' + "\n".join(body)
            )
            manifest["apis"].append(
                {
                    "contract": contract["id"],
                    "python": f"AsyncBpiClient.{domain}.{name}",
                    "module": f"src/bpi/_generated/{domain}_client.py",
                    "status": "generated",
                    "response": annotation,
                    "risk": contract["risk"],
                }
            )
            kwargs: Record = {}
            query = contract["request"].get("query", {})
            if endpoint.get("video_id"):
                kwargs.update(
                    {
                        k: int(v) if k == "aid" else v
                        for k, v in query.items()
                        if k in {"aid", "bvid"}
                    }
                )
            for param in endpoint["params"]:
                wire = param.get("wire", param["name"])
                if wire in query:
                    raw = query[wire]
                    kind = param.get("kind", "int")
                    if kind == "bool":
                        allowed = (
                            {"0": False, "1": True}
                            if param["encoding"] == "01"
                            else {"false": False, "true": True}
                        )
                        kwargs[param["name"]] = allowed[raw]
                    elif kind == "int":
                        kwargs[param["name"]] = int(raw)
                    elif kind == "int_list":
                        kwargs[param["name"]] = [int(value) for value in raw.split(",")]
                    elif kind == "str_list":
                        kwargs[param["name"]] = raw.split(",")
                    else:
                        kwargs[param["name"]] = raw
            manifest["cases"].append(
                {
                    "contract": contract["id"],
                    "contract_path": contract["path"],
                    "domain": domain,
                    "method": name,
                    "kwargs": kwargs,
                    "signed": bool(method["signing_evidence"]),
                    "batch": endpoint.get("batch", "3"),
                }
            )
        models_import = (
            f"from .{domain}_models import {', '.join(sorted(imports))}\n" if imports else ""
        )
        external_client_imports = (
            "\n".join(sorted(client_external_imports)) + "\n" if client_external_imports else ""
        )
        class_name = domain.title() + "ReadMethods"
        content = HEADER + (
            "from __future__ import annotations\nfrom typing import TYPE_CHECKING\n"
            "from pydantic import ConfigDict, TypeAdapter\n"
            "from bpi.errors import InvalidParameterError\n"
            "from bpi._core.params import integer, video_id\n"
            + models_import
            + external_client_imports
            + "if TYPE_CHECKING:\n    from bpi.client import AsyncBpiClient\n\n"
            + "\n".join(adapters)
            + f"\n\nclass {class_name}:\n"
            "    def __init__(self, client: AsyncBpiClient) -> None:\n"
            "        self._client = client\n\n" + "\n\n".join(methods) + "\n"
        )
        outputs[f"src/bpi/_generated/{domain}_client.py"] = format_python(content)
        outputs[f"src/bpi/_generated/{domain}_models.py"] = format_python(emitter.render())
    outputs["migration/generated/batch-3.json"] = json.dumps(manifest, indent=2) + "\n"
    return outputs


def write_outputs(root: Path, outputs: dict[str, str], *, check: bool) -> None:
    for name in outputs:
        path = (root / name).resolve()
        if not path.is_relative_to(root.resolve()):
            raise ValueError("Output escapes workspace")
        if (
            path.exists()
            and name.endswith(".py")
            and not path.read_text(encoding="utf8").startswith((HEADER, OLD_HEADER))
        ):
            raise ValueError(f"Refusing to overwrite handwritten file: {name}")
    if check:
        stale = [
            name
            for name, content in outputs.items()
            if not (root / name).is_file() or (root / name).read_text(encoding="utf8") != content
        ]
        if stale:
            raise ValueError(f"Generated outputs differ: {', '.join(stale)}")
        return
    for name, content in outputs.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf8")


def load_spec(root: Path) -> Record:
    result: Record = {
        "endpoints": [],
        "model_defaults": {},
        "model_names": {},
        "external_models": {},
        "external_types": {},
    }
    for path in sorted((root / "migration").glob("batch-*.json")):
        batch = json.loads(path.read_text(encoding="utf8"))
        if "source_commit" in result and result["source_commit"] != batch["source_commit"]:
            raise ValueError("Batch source commits differ")
        result["source_commit"] = batch["source_commit"]
        result["endpoints"].extend(
            {**e, "batch": path.stem.removeprefix("batch-")} for e in batch["endpoints"]
        )
        for group in ("model_defaults", "model_names", "external_models", "external_types"):
            for key, value in batch.get(group, {}).items():
                if key in result[group] and result[group][key] != value:
                    raise ValueError(f"Conflicting {group}: {key}")
                result[group][key] = value
    if not result["endpoints"]:
        raise ValueError("No batch specifications found")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    inventory = json.loads((root / "migration/generated/inventory.json").read_text(encoding="utf8"))
    try:
        spec = load_spec(root)
        outputs = render(inventory, spec)
        write_outputs(root, outputs, check=args.check)
    except (ValueError, KeyError) as error:
        parser.exit(1, f"Generation failed: {error}\n")
    print(f"{'Checked' if args.check else 'Generated'} {len(outputs)} files")


if __name__ == "__main__":
    main()
